### ISSUE TITLE
Microsoft Visual C++ Runtime Error when loading model

### ISSUE THREAD

**Issue by argman** [Microsoft/Windows-Machine-Learning#100]
## I'm submitting a…

  

Bug report

## Current behavior

in base.h it throws throw hresult_error(result, hresult_error::from_abi);

![image](https://user-images.githubusercontent.com/15120999/49352577-9c9fbc00-f6f3-11e8-8a17-a44bd4d6c7ec.png)

## Minimal reproduction of the problem with instructions

Just compile and run the exe with command line
.\SqueezeNetObjectDetectionCPP.exe F:\VSProjects\source\repos\Windows-Machine-Learning\SharedContent\models\SqueezeNet.onnx  "图片\1.jpg" cpu

## Environment

Windows Build Number: 10.0.17134

App min and target version:

OS Version (Server, IoT Core, Desktop, etc): Desktop

Graphics Driver version: CUDA9.0

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )15.9.3
- [ ] 2017 Preview (version: )

**Comment by ryanlai2** [comment]
Hi argman, thank you for filing an issue! May I ask if you built the sample SqueezeNetObjectDetectionCPP application with the [target SDK version 17763](https://github.com/Microsoft/Windows-Machine-Learning/blob/master/Samples/SqueezeNetObjectDetection/Desktop/cpp/SqueezeNetObjectDetectionCPP.vcxproj#L12)?

The target Windows Build number for this sample is 17763 (Windows 10 October 2018 Update). It should also work on builds higher this (if you have access to Windows Insider Preview).
