### ISSUE TITLE
WinMLRunner build failure

### ISSUE THREAD

**Issue by ssgwos** [Microsoft/Windows-Machine-Learning#123]
## I'm submitting a Possible Bug with WinMLRunner (StaticLib)…

Static lib doesn't build, tried many SDK versions, Visual Studio 2017 and Win 10 x64 Release.
Error	C2664	'winrt::array_view<const uint8_t>::array_view(winrt::array_view<const uint8_t> &&)': cannot convert argument 1 from 'const int8_t *' to 'const unsigned char *'	WinMLRunnerStaticLib	c:\program files (x86)\windows kits\10\include\10.0.17763.0\cppwinrt\winrt\base.h	3343	

## Environment

Windows Build Number:

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by ryanlai2** [comment]
Apologies for the build error! The latest version should build.
