### ISSUE TITLE
Runtime Error , while loading the model

### ISSUE THREAD

**Issue by iamshri8** [microsoft/Windows-Machine-Learning#130]
Hi,

I tried following your example - to load SqueezedNet.onnx into the project. It loaded successfully.

While I am trying to load my own ONNX model, I am getting the following runtime error,

![capture](https://user-images.githubusercontent.com/31486526/51428340-e4769600-1c02-11e9-8f53-43aa1c54b26f.PNG)

Could someone please help me on this?

**Comment by iamshri8** [comment]
More information about the issue: Converted my Keras to TensorFlow model and then converted into ONNX model using winmltools.

ONNX Version used is 1.3.0.


I am not sure if the problem is related to my ONNX or os some other issue ? 
Could someone help on this ?

**Comment by ryanlai2** [comment]
Hi @iamshri8 , thank you for reporting this issue and sharing your ONNX model. I will be looking at this for you, would you be able to share your source Tensorflow model? :)

**Comment by iamshri8** [comment]
@ryanlai2

Yes. Please find my tensorflow model.

https://drive.google.com/open?id=168iozr9-kycmwb4HapH-PFy1O7hAuDr1
