### ISSUE TITLE
Type Error : Type parameter (T) bound to different types (tensor(float) and tensor(int32) in node (conv2d_transpose_4/mul).

### ISSUE THREAD

**Issue by Rathna21** [Microsoft/Windows-Machine-Learning#132]
Now I am trying to build an Windows ML app in .Net Core. So, while I am loading my onnx model i am getting the following error:

Type Error : Type parameter (T) bound to different types (tensor(float) and tensor(int32) in node (conv2d_transpose_4/mul).
![capture](https://user-images.githubusercontent.com/34045027/51484880-f2f8b500-1d9c-11e9-858b-b1df38f3baa0.png)

Is there a way I can resolve this error ?

**Comment by ryanlai2** [comment]
Hi @Rathna21 , thank you for reporting this issue! This error occurs when your operator's type-parameter T is bound to different values for different inputs. Mul operator has 2 parameters A and B. According to ONNX documentation, they both must be the same type : https://github.com/onnx/onnx/blob/master/docs/Operators.md#Mul

In your case, it looks like you have a Mul operator node with two different types: Tensor(float) and Tensor(int32). You must have them both be the same type: either both Tensor(float) or Tensor(int32)

**Comment by Rathna21** [comment]
@ryanlai2 

Thanks for the reply. I figured out to change the types for multiplication operation. Now, I am successfully able to load my model in Windows ML.
I was able to load the image as well.

But unfortunately, I am stuck in binding my input to the model. 

I used the following code to load and bind my model but i am getting following error:

**_session = new LearningModelSession(_model, new LearningModelDevice(_deviceKind));

            Console.WriteLine("Loading the image...");
            ImageFeatureValue imageTensor = LoadImageFile();**   // Image successfully loads here.


  **// create a binding object from the session
            Console.WriteLine("Binding...");
            LearningModelBinding binding = new LearningModelBinding(_session);
            binding.Bind(_model.InputFeatures.ElementAt(0).Name, imageTensor);    
            Console.WriteLine("BindingDone");**

      **private static ImageFeatureValue LoadImageFile()
        {
            StorageFile imageFile = AsyncHelper(StorageFile.GetFileFromPathAsync(_imagePath));
            

            IRandomAccessStream stream = AsyncHelper(imageFile.OpenReadAsync());
            BitmapDecoder decoder = AsyncHelper(BitmapDecoder.CreateAsync(stream));
            SoftwareBitmap softwareBitmap = AsyncHelper(decoder.GetSoftwareBitmapAsync());
            softwareBitmap = SoftwareBitmap.Convert(softwareBitmap, BitmapPixelFormat.Rgba8, BitmapAlphaMode.Premultiplied);
            Console.WriteLine(softwareBitmap.ToString());
            VideoFrame inputImage = VideoFrame.CreateWithSoftwareBitmap(softwareBitmap);
            
            return ImageFeatureValue.CreateFromVideoFrame(inputImage);
        }**

// getting the below error in the line  binding.Bind(_model.InputFeatures.ElementAt(0).Name, imageTensor);   .

This is the image I am trying to load.
![test](https://user-images.githubusercontent.com/34045027/51567425-75659f80-1e97-11e9-92c9-41267813bb19.png)

The error is - 
![capture](https://user-images.githubusercontent.com/34045027/51567506-a5ad3e00-1e97-11e9-83c4-ea47c566a227.PNG)


But when i try the squeezednet example, the image is successfully converted into float { 1, 3, 224, 224 }
But I am getting the above error.

Could you please assist me on this ?

**Comment by Rathna21** [comment]
@ryanlai2 

My model expects the input in the shape float { 1, 3, 512, 256 } , but the code above fails to convert the image into this type. 

I have trained my model by normalizing the image pixel values to be between -1 and 1 and then train, so is this the problem?

Could you please assist me on this?

**Comment by Rathna21** [comment]
@ryanlai2 

I tried to do further investigation on the issue and tried in c++.

I did the following - 
1. did own customization
2. and ran in debug mode 
I am getting the following exception

![capture](https://user-images.githubusercontent.com/34045027/51610527-3f6afe80-1f1d-11e9-94a7-db67bb951e85.PNG)

I have a doubt - while training i have normalized the pixel values to -1 to 1 and then trained it so while binding the input should i do this or can i do after binding?


Could you please answer me this and help me?

**Comment by ryanlai2** [comment]
Hi @Rathna21 , Glad I was able to assist you with your issue on loading the model! Would you be able to share your ONNX model so we can investigate? If you open your ONNX model with Netron tool and look at the input variable (input_1_0), can you tell me what shape that is? 

It looks like it's expecting Float[1, 256, 512, 3] based on your error screenshot.

**Comment by Rathna21** [comment]
@ryanlai2 
Thanks for the reply.  

Please find the attached onnx model.  

You can have the attached model from netron. As you said the model expects Float[1, 256, 512, 3].
![capture](https://user-images.githubusercontent.com/34045027/51766944-32e0d480-20dc-11e9-9adc-40b18c65c8dd.PNG)


And while training I have converted the image into 4d numpy array and loaded into the model. So, should I convert the image to 4d array and then bind? As I run SqueezeNet example, I guess the model expects as image as an input and my model expects a 4d numpy array as an input.

When i went through the docs, it says Tensorization happens during evaluation so I am little confused. Could you please clarify this?

Please find the attached function I used while testing in Keras, 
![capture1](https://user-images.githubusercontent.com/34045027/51767324-45a7d900-20dd-11e9-99f5-8586800494a3.PNG)


It would be grateful if you could help me on this?

**Comment by ryanlai2** [comment]
Hi @Rathna21 , thank you for catching our documentation bug :) Tensorization actually happens on bind, NOT evaluation. 

I am currently investigating your issue, it would be very helpful if you would be able to share your source models that you used to convert to ONNX. You mentioned Keras, did you convert directly from Keras to ONNX?

Also, it looks like the model you attached in your previous comment (keras_onnx_direct.onnx) doesn't have the conv2d_transpose_4/mul operator? Is this a different model than the one you started this issue with? It seems similar to this issue in the sense that the conv2d_transpose_4/mul operator exists in that person's source model: https://github.com/Microsoft/Windows-Machine-Learning/issues/130#issuecomment-455795212

**Comment by youngkim93** [comment]
Hi @Rathna21 I'll close this issue for now due to inactivity. Feel free to reopen the case if you are still running into issues.

**Comment by ajaysg** [comment]
@Rathna21 can u please advise on how u solved the type parameter issue. i am having a similar issue  in onnxrt with my onnx model

**Comment by WilliamZhaoz** [comment]
> @ryanlai2
> 
> Thanks for the reply. I figured out to change the types for multiplication operation. Now, I am successfully able to load my model in Windows ML.
> I was able to load the image as well.
> 
> But unfortunately, I am stuck in binding my input to the model.
> 
> I used the following code to load and bind my model but i am getting following error:
> 
> **_session = new LearningModelSession(_model, new LearningModelDevice(_deviceKind));
> 
> ```
>         Console.WriteLine("Loading the image...");
>         ImageFeatureValue imageTensor = LoadImageFile();**   // Image successfully loads here.
> ```
> 
> **// create a binding object from the session Console.WriteLine("Binding..."); LearningModelBinding binding = new LearningModelBinding(_session); binding.Bind(_model.InputFeatures.ElementAt(0).Name, imageTensor); Console.WriteLine("BindingDone");**
> 
> ```
>   **private static ImageFeatureValue LoadImageFile()
>     {
>         StorageFile imageFile = AsyncHelper(StorageFile.GetFileFromPathAsync(_imagePath));
>         
> 
>         IRandomAccessStream stream = AsyncHelper(imageFile.OpenReadAsync());
>         BitmapDecoder decoder = AsyncHelper(BitmapDecoder.CreateAsync(stream));
>         SoftwareBitmap softwareBitmap = AsyncHelper(decoder.GetSoftwareBitmapAsync());
>         softwareBitmap = SoftwareBitmap.Convert(softwareBitmap, BitmapPixelFormat.Rgba8, BitmapAlphaMode.Premultiplied);
>         Console.WriteLine(softwareBitmap.ToString());
>         VideoFrame inputImage = VideoFrame.CreateWithSoftwareBitmap(softwareBitmap);
>         
>         return ImageFeatureValue.CreateFromVideoFrame(inputImage);
>     }**
> ```
> 
> // getting the below error in the line binding.Bind(_model.InputFeatures.ElementAt(0).Name, imageTensor); .
> 
> This is the image I am trying to load.
> ![test](https://user-images.githubusercontent.com/34045027/51567425-75659f80-1e97-11e9-92c9-41267813bb19.png)
> 
> The error is -
> ![capture](https://user-images.githubusercontent.com/34045027/51567506-a5ad3e00-1e97-11e9-83c4-ea47c566a227.PNG)
> 
> But when i try the squeezednet example, the image is successfully converted into float { 1, 3, 224, 224 }
> But I am getting the above error.
> 
> Could you please assist me on this ?

Hi @Rathna21 
You said you "change the types for multiplication operation" then solved the bugs.
Could you please tell me more details about how you change it, Now I hit the same problem, but I do not know where the problem is, I do not know which var is in a wrong data type.

Thank you.

**Comment by LPBourret** [comment]
@WilliamZhaoz Hi, I see that your image is 512x256 and that your model defines the input as a tensor with a shape in the NHW***C*** format [1, 256, 512, ***3***]. 
The automatic tensorization using an image tensor works for image tensors of shape N***C***HW, i.e. you'd need the input to be defined as [1, ***3***, 256, 512]. 
If you wanted, you could edit your model and change your metadata so that the input is of the NCHW shape and then insert a [transpose operator](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Transpose) right after the input in your graph (i.e. Transpose(0,3,1,2) ). You can also just do a manual tensorization to the format needed here like the custom tensorization sample does but modified for your particular shape with the *C* permuted (see [SoftwareBitmapToSoftwareTensor](https://github.com/microsoft/Windows-Machine-Learning/blob/master/Samples/CustomTensorization/CustomTensorization/TensorConvertor.cpp))
