### ISSUE TITLE
Cannot create session with GPU device

### ISSUE THREAD

**Issue by sw6y15** [microsoft/Windows-Machine-Learning#139]
## I'm submitting a…

Bug report (I searched for similar issues and did not find one) 

### WinML UWP
It cannot create learning model session with GPU.
![image](https://user-images.githubusercontent.com/29120664/51659333-2594ee80-1fe5-11e9-9884-3bbb10c80df7.png)

### WinMLRunner
I also tried to use 
` WinMLRunner.exe -model Squeeze.onnx`
And it crush as below.
![image](https://user-images.githubusercontent.com/29120664/51659919-05662f00-1fe7-11e9-919e-5adb88dcffee.png)

When I try to debug it, it also got error in create learning model session with GPU.
![image](https://user-images.githubusercontent.com/29120664/51660037-68f05c80-1fe7-11e9-9e3f-dd84652a0d2e.png)

## Minimal reproduction of the problem with instructions
code in UWP
`_device = new LearningModelDevice(LearningModelDeviceKind.DirectX);`
`_session_gpu = new LearningModelSession(_model, _device);`

## Environment

Windows Build Number:
Win 10 v1809
App min and target version:
build version 17763
OS Version (Server, IoT Core, Desktop, etc):
Desktop
Graphics Driver version:
![image](https://user-images.githubusercontent.com/29120664/51658878-41e45b80-1fe4-11e9-815c-5d89384b3122.png)

![image](https://user-images.githubusercontent.com/29120664/51658688-def2c480-1fe3-11e9-8fb8-8e90635d913d.png)

DxDiag:
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
          Input Tab: No problems found.

Visual Studio 
2017

**Comment by walrusmcd** [comment]
hello @sw6y15 ; Curious why did you close this.  did you figure out what is wrong and it's all good now?
we would like to help you fix it.

**Comment by sw6y15** [comment]
I am not sure the reason, but I clean the environment and it works now. And I found that , if I install CUDA, it happens again. Cuz I was trying onnxruntime with CUDA.

**Comment by wchao1115** [comment]
Do you happen to use any of these features when you repro the crash described here?

1. NvCpl FXAA.
2. NvCpl MFAA.
3. Ansel.
4. Shadowplay
5. Gsync

**Comment by sw6y15** [comment]
I didn't use those features manually, if these turn on by default or not?
