### ISSUE TITLE
Example for using WinML in C# application (Console, WPF, WinForms)

### ISSUE THREAD

**Issue by nietras** [Microsoft/Windows-Machine-Learning#14]
It would be great if an example for how to use WinML for a non-UWP application would be provided. And guidance around this.

**Comment by walrusmcd** [comment]
Hello!    we have now provided a sample for non-UWP.   Check out the SqueezeNet desktop app [here](https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Samples/SqueezeNetObjectDetection/Desktop/cpp).

**Comment by nietras** [comment]
Isn't that a C++ example? We did ask for a .NET C#, is that in the horizon?

**Comment by solarflarefx** [comment]
@nietras Were you ultimately able to get your application to work in .NET C#?

**Comment by nietras** [comment]
@solarflarefx no. Didn't spent much time on it since no examples were given. Instead, ended up using OnnxRuntime. :)

**Comment by mentorfloat** [comment]
@nietras What are your thoughts after using OnnxRuntime? There is now a sample for .Net Core app. https://github.com/microsoft/Windows-Machine-Learning/tree/master/Samples/SqueezeNetObjectDetection/NETCore/cs
I'm considering OnnxRuntime too but wondered if one is better than the other for Windows 10.
