### ISSUE TITLE
Chest X-Ray Images Sample

### ISSUE THREAD

**Issue by acarum** [Microsoft/Windows-Machine-Learning#17]
Where Could I download the sample for Chest X-Ray Images mentioned here ?
https://channel9.msdn.com/Shows/AI-Show/Intelligent-Edge-How-3-lines-of-code--Windows-ML-empower-devs-to-run-AI-locally-on-Win-10-devices

**Comment by walrusmcd** [comment]
Hello, the sample that talk had was for the PCB custom vision model.    We don't have the chest xray images as a public sample.   What are you trying to get done, and we can help you get started.  thanks !

**Comment by kumraj** [comment]
reopen if the issue is not resolved.
