### ISSUE TITLE
Fix SaveTensor unit tests

### ISSUE THREAD

**Issue by pmbrown1055** [Microsoft/Windows-Machine-Learning#174]
## I'm submitting a…

- Bug report (I searched for similar issues and did not find one)
The current Save Tensor unit tests run, create a directory based on time, save out tensor data to a different directory a few seconds later, and incorrectly pass because open file result is never checked in the test.

## Current behavior

Always reproduces for all architectures.

## Expected behavior

- Save Tensor unit tests would be passed a directory with a subdir based on the unit test name so the tests can run in parallel without overwriting each other.
- Tests would then successfully perform the comparison and file if files are not found, or if the results are incorrect.

## Environment

Windows Build Number:

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by ryanlai2** [comment]
Hi @pmbrown1055 , the save tensor unit tests have been caught and fixed as of this [commit](https://github.com/Microsoft/Windows-Machine-Learning/commit/014a0924b57056fd243b8cfde47a7e1ebf50637f). I'll be adding fp16 tensor output unit tests in a PR soon. I will improve that helper method that compares the tensor values so it's more clean.
