### ISSUE TITLE
What is the relationship between this project and the ML.NET project?

### ISSUE THREAD

**Issue by sharpwood** [microsoft/Windows-Machine-Learning#182]

**Comment by walrusmcd** [comment]
That's a broad question :) 

ML.NET has a great set of documentation [here](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet) .

ML.NET works very closely with dotnet applications for a wide array of tasks, training, transformations, and predictions.   You can include this package with your application to take advantage of it.

Windows Machine Learning is a set of API's that are built directly into windows.   You can consume them via the Windows API set.   It is tailored to hardware optimized tasks largely around predictions with cameras, images, and video streams.    It does them very very fast and works with windows to make them hardware accelerated. 

Does that help ?    Did you have a specific feature or question in mind we can help with that also .

thanks!

**Comment by sharpwood** [comment]
I have been learning about ML.NET projects, but I recently found that the latest version of this project does not support UWP. There are other people in the community who have the same doubts as me, [#2403](https://github.com/dotnet/machinelearning/issues/2403)
 I want to know if Windows ML can be a replacement for this issue.

**Comment by tjrileywisc** [comment]
Does MS have any plans to consolidate their ML libraries into one? CNTK just released their last major update, and between ML.NET and Windows ML there doesn't appear to be any MS libraries that allow training of neural networks, just inference. CNTK allowed that, but it's gone into maintenance mode.

**Comment by LPBourret** [comment]
Hi,
You can train models with ML.net ([see reference](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-machine-learning-model-ml-net)) and export to ONNX format using the [available converter](https://www.nuget.org/packages/Microsoft.ML.OnnxConverter/). 
You can also train models and retrieve them in ONNX format using Azure services such as [Custom Vision](https://azure.microsoft.com/en-us/services/cognitive-services/custom-vision-service/) ([see reference here](https://docs.microsoft.com/en-us/azure/machine-learning/service/concept-onnx)). 
You can also use your other framework of choice and convert your model to ONNX ([see reference](https://docs.microsoft.com/en-us/windows/ai/windows-ml/convert-model-winmltools))

**Comment by LPBourret** [comment]
feel free to reopen
