### ISSUE TITLE
Create Device with an Adapter Index on WinMLRunner

### ISSUE THREAD

**Issue by pmbrown1055** [microsoft/Windows-Machine-Learning#183]
## I'm submitting a…

  
- Sample app request
- Request that WinMLRunner be able to create a device with a passed in Adapter Index.  Enable targeted debug on specific device.  Not worried if the device is created in WinMLRunner or by WinML itself.

## Environment

Windows Build Number:

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by martinb35** [comment]
@pmbrown1055 - we added the [GPUAdapterName](https://github.com/microsoft/Windows-Machine-Learning/blob/master/Tools/WinMLRunner/src/CommandLineArgs.cpp#L37) parameter a while ago that should address this. I believe indices can change between boot sessions, so we decided to choose by specifying the name.
