### ISSUE TITLE
System.InvalidOperationException:“Sequence contains no elements” in windows sdk 10.0.17134

### ISSUE THREAD

**Issue by veyvin** [microsoft/Windows-Machine-Learning#19]
mnist_demo  this line    var maxIndex = ModelOutput.Plus214_Output_0.IndexOf(ModelOutput.Plus214_Output_0.Max());

**Comment by walrusmcd** [comment]
Hello !   what are you trying to do ?      Can you try this with the latests SDK (17723) and insider build (17733) and send the details.   We will totally get you running !
