### ISSUE TITLE
Add Batch > 1 capability to WinMLRunner

### ISSUE THREAD

**Issue by pmbrown1055** [microsoft/Windows-Machine-Learning#192]
## I'm submitting a…

Feature Request
- Add the ability to process batch size > 1.  This should allow multiple images to be loaded in WinMLRunner and be batched to the hardware, to try and optimize compute throughput.

## Environment

Windows Build Number:

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by Adele101** [comment]
Thank you for your request. The Windows ML team is taking this idea under consideration as we plan new features.

If there are others who have this feature request, please feel free to comment and let us know how it would be helpful for you.
