### ISSUE TITLE
Add median performance summary data to printed performance summary with -perf option

### ISSUE THREAD

**Issue by pmbrown1055** [microsoft/Windows-Machine-Learning#197]
## I'm submitting a…

Feature Request
- Currently the performance summary has a lot of great information.  It would be good to also include the median performance times in the summary (in addition to the mean time currently displayed).

  

## Environment

Windows Build Number:

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by Adele101** [comment]
Thank you for your request. The Windows ML team is taking this idea under consideration as we plan new features.

If there are others who have this feature request, please feel free to comment and let us know how it would be helpful for you.
