### ISSUE TITLE
Error while evaluating the model which is converted from Keras to ONNX

### ISSUE THREAD

**Issue by Rathna21** [microsoft/Windows-Machine-Learning#205]
Hello,

I have built a model in Keras and I successfully converted into ONNX. I have to load to converted ONNX model into Windows ML. 

The Windows ML by-default accepts Input shape as { batch_size, channels, height, width}

But my onnx model accepts the input shape as { batch_size , height, width, channels }

Because of this while binding the model to input in Windows ML i am getting an error. 
So how can i handle this in Windows ML?

Could someone please answer for this?

Thanks,
Rathna

**Comment by ryanlai2** [comment]
Hi @Rathna21 , thanks for asking this question! Just need some more clarity: do you plan on passing images (videoframe) through your ONNX model? Which tool did you use to convert your Keras model to ONNX?

**Comment by Rathna21** [comment]
Thanks for the reply.


I am using onnxmltools to convert my Keras model to ONNX model.

I cannot pass it as a Video frame because windows ML by default accepts the shape { batch_size, channels, height, width }

But my input shape is different?

So, I am not sure how to proceed on this further? 

@ryanlai2  It would be great if you help me on this?

**Comment by ryanlai2** [comment]
I am happy to help you with this! Would you be able to share your source Keras model for repro purposes? :)

**Comment by youngkim93** [comment]
@Rathna21 Have you tried passing in the input name in channel_first_inputs { batch_size, channels, height, width } as shown here? https://github.com/onnx/keras-onnx/blob/master/keras2onnx/main.py#L61

**Comment by Rathna21** [comment]
@ryanlai2 Ok thanks for such a fast reply:)

Please find my Keras model.
https://drive.google.com/file/d/1y2TP-2mhDkgkCOJKBTvPdAE0hTPJuECd/view?usp=sharing

**Comment by Rathna21** [comment]
@youngkim93 . No I did not try this. I just used onnxmltools to convert my Keras model to ONNX.

**Comment by Rathna21** [comment]
@youngkim93  I tried using the script you said as follows,

But still my input shape remains as { batch_size, height, width, channels }

Windows ML need input in the shape { batch_size, channels , height, width }

**Comment by youngkim93** [comment]
Sorry I might have confused you here. I think for channel_first_inputs you would have to actually pass in the name of the input of a model.

**Comment by youngkim93** [comment]
@wenbingl Hi Wenbing, could you help with this issue? it seems like the model is doing unnecessary transpose at the very end. Is there any way to specify the channel_first for outputs as well?

**Comment by Rathna21** [comment]
@youngkim93  Did you find some solution for this?

**Comment by Rathna21** [comment]
@youngkim93 

As u said yesterday I converted my model with keras2onnx script. Now the model has changed its input shape but there are 2 problems:

1. outshape shape is transposed
2. If i try to load the converted onnx model into Windows ML and run the model and try printing all the output values, they are all zero.

I am stuck with these 2 problems.

Could you somehow help me on this?

**Comment by ryanlai2** [comment]
Closing this because issue that was referenced was resolved. @Rathna21 please reopen this issue if assistance still  needed.
