### ISSUE TITLE
Custom Tensorization example in C# for Hololens/UWP

### ISSUE THREAD

**Issue by joaocc** [microsoft/Windows-Machine-Learning#227]
Hi,
Is anyone working on a sample for Custom Tensorization that can run on C# for Hololens/UWP?
Thank

**Comment by ngeisler11** [comment]
HI Joaocc,

We are currently not working on a C# sample for custom tensorization, but I have added this to our backlog of requested samples. Hopefully in the near future we will have one available. Thank you for the feedback/request.

**Comment by yoKurt94** [comment]
Is there by now a way (sample code) to convert a SoftwareBitmap to a TensorFloat in C#? I have the exact same issue as in [here](https://github.com/microsoft/Windows-Machine-Learning/issues/257) but there is still no appropiate answer to this issue. Or are there any other workarounds I am not aware of?
