### ISSUE TITLE
Conversion from TensorFlow model to ONNX using winml tools

### ISSUE THREAD

**Issue by anujonthemove** [microsoft/Windows-Machine-Learning#240]
## I'm submitting a…

- I am opening this issue regarding conversion of a TensorFlow model to ONNX format, couldn't find any open issue here. 

- The example defined in [this](https://docs.microsoft.com/en-us/windows/ai/windows-ml/convert-model-winmltools#convert-tensorflow-models) Microsoft docs page is a bit incomplete, for anyone new attempting to use this would not get the desired result. 
 
- I have made minor changes and made it work, it can be found [here](https://github.com/anujonthemove/Computer-Vision-Playground/blob/master/deep-learning/exploring-tensorflow/TensorFlow_to_ONNX_using_winmltools.ipynb)

_Please correct the documentation on Microsoft docs page._ 

  

## Current behavior

- In the given example, necessary imports are missing along with some of the mandatory parameters have not been set which results in an error when converting a TensorFlow frozen model to an onnx model. 

## Expected behavior

On providing the path to frozen model, model output(tensor names), path to save onnx model, the example should generate a .onxx model file.

## Minimal reproduction of the problem with instructions

Copy-paste the example in a jupyter notebook, provide the path to frozen model and run it. 

## Environment

Windows Build Number:
**_Not using a Windows machine. Since this is a Python example, it is expected to work on any OS provided the required dependencies are met. I have installed winmltools from [this](https://pypi.org/project/winmltools/) link and by fixing the above mentioned issues, I have made it work._**

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

- NVIDIA GeForce 940MX (Maxwell Architecture), 4GB vRAM
- NVIDIA 410

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by youngkim93** [comment]
Hi @anujonthemove. Thanks for pointing out the missing imports! I will ask around to fix the documentation to update those headers.

**Comment by ryanlai2** [comment]
I'm closing this issue, but feel free to reopen if more assistance is needed.
