### ISSUE TITLE
Crash in AdapterSelection sample...

### ISSUE THREAD

**Issue by JohnCraigPublic** [microsoft/Windows-Machine-Learning#241]
Possible Bug Report

I run the AdapterSelection sample, and see this in the transcript...

Index: 0, Description: NVIDIA GeForce RTX 2080 Ti
Please enter the index of the adapter you want to use...
0
Selected adapter at index 0
Loading modelfile 'C:\Users\John\Test\squeezenet1.1.onnx' on the selected device
model file loaded in 16 ticks
Loading the image...
Binding...
Running the model...

then pops up the Abort/Ignore/Retry panel

Used VS2017,  SDK 17763, the model is the squeezenet model downloaded from ONNX Zoo.

Maybe its not enough for you to debug -- but what sorts of things *might* it be?    Thanks!

**Comment by JohnCraigPublic** [comment]
Another clue: I downloaded/installed WinMLDashboard and with it, I could load this same model, and I could run it successfully on the same image.   So, something wrong with my environment to build the AdapterSelection sample?

**Comment by ryanlai2** [comment]
Hi @JohnCraigPublic , thanks for reaching out to us for this issue! May I ask what OS Build version you are running the Squeezenet Sample on? Also can you link the exact squeezenet model you used for repro purposes? Thanks!

**Comment by JohnCraigPublic** [comment]
On Windows 10 version 1903  build 18362.116
The squeezenet is called squeezenet1.1.onnx -- from the Zoo -- file size 4,956,208 bytes

**Comment by ryanlai2** [comment]
Hi @JohnCraigPublic , may I ask what driver version your GPU is? You can find out the driver version through DxDiag

**Comment by JohnCraigPublic** [comment]
version 25.21.14.1917
GPU is NVIDIA GeForce RTX 2080 Ti

**Comment by JohnCraigPublic** [comment]
I re-did, making sure I used the Squeezenet model supplied with the example (rather than some other one I found floating around) and now it all works.
