### ISSUE TITLE
SSD mobilenet v1 support

### ISSUE THREAD

**Issue by donaparker01** [microsoft/Windows-Machine-Learning#242]
I was wondering if you supported SSD Mobilenet v1 opset 10, which allows the use of nms. If not, I am  receiving the following issue:

C:\Users\t\Downloads\WinMLRunner_v1.2.0.1\WinMLRunner_v1.2.0.1\x64>WinMLRunner.exe -model ssd_mobilenet_v1_coco_2017_11_17\output_model.onnx -iterations 200
Loading model (path = ssd_mobilenet_v1_coco_2017_11_17\output_model.onnx)...
Load Model: ssd_mobilenet_v1_coco_2017_11_17\output_model.onnx [FAILED]
Nodes in a graph must be topologically sorted, however input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack/2:0' of node:
input: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack/2:0" output: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack_Unsqueeze__2306:0" name: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack_Unsqueeze__2306" op_type: "Unsqueeze" attribute { name: "axes" ints: 0 type: INTS } domain: ""
 is not output of any previous nodes.
Nodes in a graph must be topologically sorted, however input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack/2:0' of node:
input: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack/2:0" output: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack_Unsqueeze__2306:0" name: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/stack_Unsqueeze__2306" op_type: "Unsqueeze" attribute { name: "axes" ints: 0 type: INTS } domain: ""
 is not output of any previous nodes.

Any ideas on the problem?

**Comment by ryanlai2** [comment]
Hi @donaparker01, thanks for reaching out but WinML currently doesn't support opset 10 of ONNX.

**Comment by riaz** [comment]
Depending on the Build version only Opset 7 | 8 works with Win ML.

**Comment by ngeisler11** [comment]
Hi Donaparker01,
As Riaz mentioned, WinML currently does not support opset 10. We are continually working on updating opset support for both CPU and GPU with Windows ML and should be available in a future Windows release. 
Thanks.
