### ISSUE TITLE
Errors while executing UNet-like onnx models

### ISSUE THREAD

**Issue by lorafib** [microsoft/Windows-Machine-Learning#245]
# Bug Report for use of ONNX models with Windows-Machine-Learning Applications
(in particular an altered version of FNSCandyStyleTransfer sample)

Descriptions of current behavior can be seen below for each onnx model. In short, the purpose of my model is an image filter that gets distorted blurry images as input and should output them in "nice". 2 of 4 models aren't parsed/executed at all, 1 is executed but causes artifacts, 1 works (but doesn't fulfill the intended purpose). 

I uploaded the onnx files, data and screenshots to my drive (https://drive.google.com/open?id=1nwFLhsK0YOg0xJ2olh6Y-c22Rbn66bxO)

## System and Environment

errors can be reproduced with 
WinMLRunner.exe (dowloaded on 
‎Thursday, ‎June ‎6, ‎2019, ‏‎6:05:59 PM)

### ML Environment
python 				3.5
pytorch, onnx,... 	(see conda_env_packkages.txt)

### Rendering Machine
Windows 10 Enterprise 1903 18362.145
VS 2017, SDK 10.0.18346.0

## ONNX Models
(opset 9, might cause the trouble?)
Image filter models with an UNet-like architecture exported with pytorch (torch.onnx.export(), reloaded with onnx.load(), checked with onnx.checker.check_model(), see export.py)
All of them can be parsed by the Netron visualizer (https://lutzroeder.github.io/netron/)

My target device was the **CPU** not GPU

I prepared them to handle input according to the documentation (https://docs.microsoft.com/en-us/windows/ai/windows-ml/convert-model-winmltools)

### UNet with Upsample/ Interpolate using scale_factors arg

(using https://pytorch.org/docs/stable/nn.html#upsample)
ONNX file: UNetScaleFactorsPytorchUpsample.onnx

Error Msg: 
```
Loading model (path = .\G_model_120.onnx)...
Load Model: .\G_model_120.onnx [FAILED]
Type Error: Type 'tensor(int64)' of input parameter (63) of operator (Floor) in node () is invalid.
0000023468572A9C

```

### UNet with Upsample/ Interpolate using fixed size

ONNX file: UNetScaleCustomUpsample.onnx

After I checked the model in the Netron visualizer and the pytorch code I wrote my own dimension scaling where I added a simple float cast / tried to hardcoded the number of spatial dimensions, just to be sure.. (see CustomUpsample.py)

But now I get 
```
Loading model (path = .\polished.onnx)...
Load Model: .\polished.onnx [FAILED]
[ShapeInferenceError] Number of elements of input 'scales' must be same as rank of input 'X' and element type must be float.
000001CAD3A0810C
```

As the input dimension of my tensor and the scales factor array's length are both 4 and the types are both float I'm puzzled why this happens.

### UNet with PixelShuffle 

ONNX file: UNetPixelShuffle.onnx

Can be excuted, but causes weird artifacts (see PixelShuffle_Export239.PNG, expected outcome (executed in pytorch) see pixelshuffle_result.png)

### UNet only with Strided Conv / ConvTransposed

ONNX file: UNetConvTrans.onnx

Works fine, but doesn't converge in the first place (see UNet_Export_finally.PNG). But it validates that my out- and input have the correct format and that it works in general.

**Comment by martinb35** [comment]
hi @lorafib, the issues you are having are related to the converter process and the underlying engine, both of which live in the [OnnxRuntime repo](https://github.com/microsoft/onnxruntime/issues). If you are still seeing these problems, please open an issue in that repo. Thanks!
