### ISSUE TITLE
mlgen not generating cs file

### ISSUE THREAD

**Issue by Avrohom** [microsoft/Windows-Machine-Learning#253]
## I'm submitting a…

Bug report (I searched for similar issues and did not find one)

## Current behavior
mlgen is not generating cs files for imported ONNX models. 

I have followed the tutorial to the dot. And of course it is a UWP desktop app.

## Expected behavior
the mlgen should generate cs files.

## Minimal reproduction of the problem with instructions
Selected the Assets folder in Solution Explorer. Clicked on 'Add existing item' and imported a ONNX model. Nothing happened. No cs file generated.

## Environment

Windows Build Number: 17763

App min and target version: 17763 17763

OS Version (Server, IoT Core, Desktop, etc): Win 10 Desktop

Graphics Driver version:

DxDiag:

Visual Studio 
- [x] 2017 (version: ) Latest
- [ ] 2017 Preview (version: )

**Comment by youngkim93** [comment]
Thanks for the report. For more details, do you know which OS version you are using?

**Comment by youngkim93** [comment]
Thanks for the report. For more clarification, can you provide the visual studio version as well as the extension version?

**Comment by Avrohom** [comment]
Hi @youngkim93 ,

Visual Studio Cummunity 2017 Version 15.9.13.

And extension version: 2.6

**Comment by youngkim93** [comment]
Thanks! I'll try to repro with this information on my side. If I can't repro on my side I would have to ask you for more information about the model.

**Comment by youngkim93** [comment]
@Avrohom What's the ONNX version of your model? Is it 1.5? If so, the current extension is not supporting code generation yet.

**Comment by Avrohom** [comment]
Hi @youngkim93!

Yes, I did relized this later. It is indeed version 1.5. Any suggestion when this version will be compatible?

Also, I have tried with other models as well. Such as the MINST and the squeezenet models as well.

**Comment by youngkim93** [comment]
I can't promise when this will be released, but we are planning to release before next Windows with WinML API support of ONNX 1.5 is released for next update. This shouldn't be too far ahead from now. I will keep you posted once we get more definite dates.

**Comment by youngkim93** [comment]
Meanwhile, do you have prior version (1.3) of the same model that you would like to try adding to projects?

**Comment by Avrohom** [comment]
Many thanks for keeping me posted. I will certainly be on the lookout...

I haven't really got any version lower than 1.5. I have taken the model from the ONNX Model Zoo.

I would be very glad if someone can point out to me where I can find other versions for Mask RCNN and / or Faster RCNN.

**Comment by youngkim93** [comment]
I'm not sure there will be 1.3 version of these models. At least for Faster RCNN I see operator ConstantOfShape which is of opset 9 (ONNX 1.4)...

**Comment by ngeisler11** [comment]
Resolving this issue. Please reactivate if you are still experiencing any issues or have any additional questions.

**Comment by miyrai** [comment]
i'm experiencing the same issue with visual studio community edition 2019 with an onnx model version 1.5
