### ISSUE TITLE
Support layers with no inputs, such as Reshape/ Unsqueeze

### ISSUE THREAD

**Issue by msriram** [microsoft/Windows-Machine-Learning#254]
## I'm submitting a…

  
Sample app request

## Current behavior

```abort() has been called```
while running the network / layer with no input data. The layer is simply a reshape layer, with the data already part of the model file.

## Expected behavior

The layer should produce output using -SaveTensorData even without any -Input parameters specified

## Minimal reproduction of the problem with instructions

Rename the file to OC2_DUMMY_0.onnx and run using WinMLRunner
[OC2_DUMMY_0.onnx.txt](https://github.com/microsoft/Windows-Machine-Learning/files/3321750/OC2_DUMMY_0.onnx.txt)
```
./WinMLRunner.exe -model OC2_DUMMY_0.onnx -SaveTensorData First output -CPU
```

## Environment

Windows Build Number:

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by ryanlai2** [comment]
Hi @msriram , thank you for your suggestion! May I ask why you are looking to save tensor data with a network with no input?

**Comment by ryanlai2** [comment]
Hi @msriram, feel free to reopen if this is still an issue.
