### ISSUE TITLE
LearningModel.LoadFromStorageFileAsync faster_cnn or mask rcnn model results in "Unspecified error\r\n\r\nUnrecognized attribute: ceil_mode" exception.

### ISSUE THREAD

**Issue by Avrohom** [microsoft/Windows-Machine-Learning#255]
## I'm submitting a…

 Bug report (I searched for similar issues and did not find one)

## Current behavior
I have downloaded the SqueezeNetObjectDetection sample. Got it running successfuly.

But then I have tried loading the faster rcnn model and got an exception with the message: "Unspecified error\r\n\r\nUnrecognized attribute: ceil_mode".
Same result when I tried loading the mask rcnn model.

## Expected behavior
To load the model.

## Environment

Windows Build Number: Windows 10, version 1809 (10.0; Build 17763)

App min and target version: Windows 10, version 1809 (10.0; Build 17763). Windows 10, version 1809 (10.0; Build 17763).

OS Version (Server, IoT Core, Desktop, etc): Win 10 Desktop

Graphics Driver version:

Visual Studio 
- [x] 2017 (very latest version: )
- [x] 2019 (very latest version: )

![image](https://user-images.githubusercontent.com/6719297/60045910-ee268d00-96bd-11e9-9ded-18ce9a6a14bd.png)

**Comment by riaz** [comment]
The onnx model has to be using opset 7 i.e onnx 1.2.1/1.2/1.2.2 model. You can go to https://github.com/onnx/models and try the models that mention opset 7 / or onnx 1.2.1 or onnx 1.2 they should be working.

**Comment by martinb35** [comment]
covered by issue #252: https://github.com/microsoft/Windows-Machine-Learning/issues/252
