### ISSUE TITLE
Improve InputImageFolder Option for WinML Runner 

### ISSUE THREAD

**Issue by kenkoyanagi** [microsoft/Windows-Machine-Learning#260]
## I'm submitting a…
Feature request to improve upon the current implementation of the "-InputImageFolder" option. 

The current implementation re-loads the model every time for each image in the Input Image Folder. 

To represent a more realistic scenario, I'd like to request an option/fix to load only once per model, then bind, evaluate, return the result for each image. 

## Current behavior

Currently, for every image present in the image folder, there is a Session Creation and Load step being done. **WinMLRunner v1.2.0.2**

Model A: 
> Image 1 - Load Model A, Bind Image 1, Session Creation, Evaluation, Return result 
> Image 2 - Load Model A, Bind Image 2, Session Creation, Evaluation, Return result 
> Image 3 - Load Model A, Bind Image 3, Session Creation, Evaluation, Return result 

## Expected behavior

I believe the workflow should be: 

Model A: 
> Load Model A, 
> Bind Image 1, Evaluation, Return result,
> Bind Image 2, Evaluation, Return result, 
> Bind Image 3, Evaluation, Return result

with Session Creation somewhere in the beginning. 

## Environment

Windows Build Number: Win10 64-bit 19H1 

App min and target version: Tested on WinMLRunner v1.2.0.2

OS Version (Server, IoT Core, Desktop, etc): Desktop 19H1

Graphics Driver version: 

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …): TF
        - WinMLTools version: v1.2.0.2

Visual Studio 
- [√] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by ryanlai2** [comment]
Hi @kenkoyanagi ,  the current flow is like this:

>> Load Model A,
>> Create Session with A and Device
>> Bind Image 1, Evaluation, Return result,
>> Bind Image 2, Evaluation, Return result,
>> Bind Image 3, Evaluation, Return result

Please look at this line in the code : https://github.com/microsoft/Windows-Machine-Learning/blob/1e210e75c95b6ebc9a6aa163841dea0df45715cc/Tools/WinMLRunner/src/Run.cpp#L866

Let me know if you have any questions or if you're still confused? If I may ask, what WinMLRunner command did you run?

**Comment by kenkoyanagi** [comment]
Hi @ryanlai2 , I see an output like the one reported with this command: 

`WinMLRunner.exe -model resnet50v2.onnx -InputImageFolder \images -Perf -GPU -SavePerIterationPerf -Terse`

**Comment by ryanlai2** [comment]
Hi @kenkoyanagi, when I run with your command with Squeezenet, I get the below output. Can you point out where you think the model is being loaded twice? The images folder has 2 images

>.\WinMLRunner.exe -model .\SqueezeNet.onnx -inputimagefolder  .\images\ -gpu -perf -saveperiterationperf -terse


=================================================================
Name: squeezenet_old
Author: onnx-caffe2
Version: 9223372036854775807
Domain:
Description:
Path: .\SqueezeNet.onnx
Support FP16: false

Input Feature Info:
Name: data_0
Feature Kind: Float

Output Feature Info:
Name: softmaxout_1
Feature Kind: Float

=================================================================


Creating Session with GPU: NVIDIA GeForce RTX 2070
Generating input feature(s) with image: \images\fish.png
Binding (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]
Evaluating (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]
Outputting top 1 values
Feature Name: softmaxout_1
 index: 0, value: 0.738501

Results (device = GPU, numIterations = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML):

First Iteration Performance (load, bind, session creation, and evaluate):
  Load: 14.9904 ms
  Bind: 2.9739 ms
  Session Creation: 87.6773 ms
  Evaluate: 6.9404 ms

  Working Set Memory usage (evaluate): 2.46484 MB
  Working Set Memory usage (load, bind, session creation, and evaluate): 25.1289 MB
  Peak Working Set Memory Difference (load, bind, session creation, and evaluate): 13.2188 MB

  Dedicated Memory usage (evaluate): 8.39453 MB
  Dedicated Memory usage (load, bind, session creation, and evaluate): 19.3516 MB

  Shared Memory usage (evaluate): 1.625 MB
  Shared Memory usage (load, bind, session creation, and evaluate): 3.31641 MB



Generating input feature(s) with image: \images\kitten_224.png
Binding (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]
Evaluating (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]
Outputting top 1 values
Feature Name: softmaxout_1
 index: 281, value: 0.931461

Results (device = GPU, numIterations = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML):

First Iteration Performance (load, bind, session creation, and evaluate):
  Load: 14.9904 ms
  Bind: 1.6921 ms
  Session Creation: 87.6773 ms
  Evaluate: 4.3341 ms

  Working Set Memory usage (evaluate): 1.29492 MB
  Working Set Memory usage (load, bind, session creation, and evaluate): 23.873 MB
  Peak Working Set Memory Difference (load, bind, session creation, and evaluate): 11.459 MB

  Dedicated Memory usage (evaluate): 4.19727 MB
  Dedicated Memory usage (load, bind, session creation, and evaluate): 14.6504 MB

  Shared Memory usage (evaluate): 0.875 MB
  Shared Memory usage (load, bind, session creation, and evaluate): 2.1543 MB

**Comment by kenkoyanagi** [comment]
@ryanlai2 , I re-ran it with a folder with two images. 

I noticed in your run and my latest run that Load and Session Creation times are the same. This is the indication that it was done only once and that the following iterations (2nd in this case) are just reporting the initial time, right? If this is the case, I can close the issue. :) 

----- 

**Command:** 
`WinMLRunner.exe -model resnet50v2.onnx -InputImageFolder .\2images -Perf -GPU -SavePerIterationPerf -Terse`

**Output:** 
Creating Session with GPU: 
**Generating input feature(s) with image: \2images\n01595974_127.jpg
Binding (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]**
Evaluating (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]
Outputting top 1 values
Feature Name: resnetv24_dense0_fwd
 index: 459, value: 16.4747

Results (device = GPU, numIterations = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML):

First Iteration Performance (load, bind, session creation, and evaluate): 
  **Load: 153.661 ms**
  Bind: 23.2999 ms
  **Session Creation: 3122.56 ms**
  Evaluate: 260.488 ms

  Working Set Memory usage (evaluate): 33.5938 MB
  Working Set Memory usage (load, bind, session creation, and evaluate): 579.578 MB
  Peak Working Set Memory Difference (load, bind, session creation, and evaluate): 590.879 MB

  Dedicated Memory usage (evaluate): 0 MB
  Dedicated Memory usage (load, bind, session creation, and evaluate): 0 MB

  Shared Memory usage (evaluate): 33.5039 MB
  Shared Memory usage (load, bind, session creation, and evaluate): 441.301 MB



**Generating input feature(s) with image: 2images\n01646802_2589.jpg
Binding (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]**
Evaluating (device = GPU, iteration = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML)...[SUCCESS]
Outputting top 1 values
Feature Name: resnetv24_dense0_fwd
 index: 409, value: 14.1831

Results (device = GPU, numIterations = 1, inputBinding = CPU, inputDataType = RGB_Image, deviceCreationLocation = WinML):

First Iteration Performance (load, bind, session creation, and evaluate): 
  **Load: 153.661 ms**
  Bind: 13.902 ms
  **Session Creation: 3122.56 ms**
  Evaluate: 130.978 ms

  Working Set Memory usage (evaluate): 16.8379 MB
  Working Set Memory usage (load, bind, session creation, and evaluate): 561.535 MB
  Peak Working Set Memory Difference (load, bind, session creation, and evaluate): 575.213 MB

  Dedicated Memory usage (evaluate): 0 MB
  Dedicated Memory usage (load, bind, session creation, and evaluate): 0 MB

  Shared Memory usage (evaluate): 16.7949 MB
  Shared Memory usage (load, bind, session creation, and evaluate): 423.775 MB

**Comment by ryanlai2** [comment]
Hi @kenkoyanagi, yes that's correct! The reporting is just reporting the initial load and session creation times.

**Comment by kenkoyanagi** [comment]
@ryanlai2 , thanks for the clarification! Would it be possible for the future version to have that differentiation in the report log? Anyways, I'll close this issue. Thanks again!
