### ISSUE TITLE
unable to open squeezenet object detection solution in visual studio 2019

### ISSUE THREAD

**Issue by priyankagupta639** [microsoft/Windows-Machine-Learning#270]
I tried to open the Squeezenet object detection sample solution file in visual studio 2019 but it is not opening. Here is the screenshot.

![ScreenshotProblem](https://user-images.githubusercontent.com/33253391/63649699-93152300-c75e-11e9-9dd7-3034d1678331.PNG)

**Comment by LPBourret** [comment]
Hi Priyanka,
to help us understand your issue, can you elaborate a bit about on your developer environment and the error when attempting to load the project. Specifically:
1) do you meet the [requirements listed](https://github.com/microsoft/Windows-Machine-Learning/edit/master/Samples/SqueezeNetObjectDetection/Desktop/cpp/README.md):
    [Windows 10 - Build 17763 or higher](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso)
    - [Windows SDK - Build 17763 or higher](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK)
    - Visual Studio Extension for C++/WinRT

      Do the following to add the C++/WinRT extension in Visual Studio.
      1. Go to **Tools > Extensions and Updates**. 
      2. Select **Online** in the left pane and search for "WinRT" using the search box.
      3. Select the **C++/WinRT** extension, click **Download**, and close Visual Studio. The extension should install automatically.
      4. When the extension has finished installing, re-open Visual Studio.

2) What is the output when you right click on the unloaded project and click "*Reload Project*"

thank you

**Comment by priyankagupta639** [comment]
I have met all the requirements. I am working on Windows 10 (latest version) and using SDK 17763

On opening the SqueezeNetObjectDetection solution as mentioned in the steps, The following dialog box pops up.
![problem window](https://user-images.githubusercontent.com/33253391/63702815-5c660800-c845-11e9-994f-724ebd5027b0.PNG)

On clicking "Ok", it generates the migration report. 
![Migration report](https://user-images.githubusercontent.com/33253391/63702946-9d5e1c80-c845-11e9-969c-bd50fed0d4e2.PNG)


This is the screen which is there in the visual studio.
![Capture1](https://user-images.githubusercontent.com/33253391/63701743-258ef280-c843-11e9-8cfe-e44759d77876.PNG)

When I right-click on the SqueezeNetObjectDetectionJS file, it shows the unavailable reload "project option".

![capture2](https://user-images.githubusercontent.com/33253391/63702100-ea40f380-c843-11e9-88c0-62ff7dee9bf1.jpeg)

**Comment by priyankagupta639** [comment]
I have now tried it with
Visual Studio 2017 
Windows 10 - Build 17763
Windows SDK - 17763
Installed the extension and changed the platform target default to both x64 and x86 separately

All the projects have been loaded successfully but the solution is not building up and showing many errors in the Program.cs file.

There are 34 errors and the error codes are CS0246 and CS0103.

The description for code CS0246 says "The type or namespace name "Windows" could not be found(are you missing a using directive or an assembly reference?)"

Below is the screenshot of the error :

![visual_studio2017](https://user-images.githubusercontent.com/33253391/63883029-dc7ca100-c9f0-11e9-83b8-608c7d3091e6.PNG)

Is there any particular workload or any individual component to be included during the installation process? 
Share the list of workloads and individual components to be included during installation. 

![image](https://user-images.githubusercontent.com/33253391/63884069-249cc300-c9f3-11e9-9dec-8633d11d26e9.png)

**Comment by priyankagupta639** [comment]
I have made the changes by crack opening SqueezeNetObjectDetectionNC.csproj project file and replace $(WINDOWS_WINMD) with a valid path.

The required output is not received.
Following is the output which I am receiving.

Also, how to see the pictures with bounding boxes and how and where to add the custom images? 


![output error](https://user-images.githubusercontent.com/33253391/63926849-2eadd880-ca6a-11e9-8952-7a10ed339650.PNG)
