### ISSUE TITLE
Inference Time Error ([ONNXRuntimeError] : 10 : INVALID_GRAPH )

### ISSUE THREAD

**Issue by jaemjaem** [microsoft/Windows-Machine-Learning#275]
`from winmltools.utils import convert_float_to_float16`
`from winmltools.utils import load_model, save_model`

`onnx_model = load_model('InputModel.onnx')`
`new_onnx_model = convert_float_to_float16(onnx_model)`
`save_model(new_onnx_model, 'OuputModel_fp16.onnx')`

`sess = rt.InferenceSession('InputModel_fp16.onnx')`

RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from new_yolo3_one_dimension.onnx failed:This is an invalid model. Type Error: Type 'tensor(float16)' of input parameter (Resize_scales) of operator (Resize) in node (Resize) is invalid.

I converted the onnx model to float 16 using winmltools.

At the reference time, there is an RuntimeError. How do I fix it??

**Comment by martinb35** [comment]
@jaemjaem - if you are still having this issue, can you please post in the [onnxruntime github issues](https://github.com/microsoft/onnxruntime/issues) section? That is where evaluation issues get tracked. Thanks!
