### ISSUE TITLE
Accept ONNX tensor files as input (bug and suggestion)

### ISSUE THREAD

**Issue by fdwr** [microsoft/Windows-Machine-Learning#276]
## I'm submitting a…

Bug report and feature suggestion.

The ONNX backend test suite contains hundreds of mini-models and corresponding input tensor files (e.g. https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/pytorch-converted/test_ConvTranspose2d), and it would be useful for WinMLRunner to be able to easily run one of these test cases for diagnosing/reproducing issues. e.g.

    cd onnx\backend\test\data\pytorch-converted\test_ConvTranspose2d
    WinMLRunner.exe -cpu -model model.onnx -input test_data_set_0\input_0.pb

This _seems_ to work (no error message seen), but it doesn't appear to actually understand the data format (ONNX Tensor file stored via .pb Protobuf format) and silently ignores it.

## Current behavior
WinMLRunner silently ignores the input file.

## Expected behavior
- WinMLRunner at least reports an error about the file type (the bug).
- WinMLRunner reads the tensor file format (the feature request).

## Minimal reproduction of the problem with instructions
See above.

## Environment

Windows Build Number: 18981 10 vb_release 2019-09-09

App min and target version: ?

OS Version (Server, IoT Core, Desktop, etc): Desktop

Graphics Driver version: NA (issue occurs independent of GPU/CPU)

WinMLTools specific:
	- Source training framework: ONNX, PyTorch
        - WinMLTools version: 1.0.0.0.190304.7e8af7e

Visual Studio: 2017 15.8.5

**Comment by Adele101** [comment]
Thank you for your request. The Windows ML team is taking this idea under consideration as we plan new features.

If there are others who have this feature request, please feel free to comment and let us know how it would be helpful for you.
