### ISSUE TITLE
c++ loading model memory exception at LearningModel::LoadFromFilePath(modelPath)

### ISSUE THREAD

**Issue by SpaceView** [microsoft/Windows-Machine-Learning#279]
in Windows 10 + Visual Studio 2019
when I'm testing the samples 
D:\Windows-Machine-Learning-master\Samples\SqueezeNetObjectDetection\Desktop\cpp
and testing this tutorial
https://docs.microsoft.com/en-us/windows/ai/windows-ml/get-started-desktop

I got the same problem: memory exception
model = LearningModel::LoadFromFilePath(modelPath);
The exception popup windows says:
0x750D2CD2 处(位于 SqueezeNetObjectDetectionCPP.exe 中)引发的异常: Microsoft C++ 异常: winrt::hresult_error，位于内存位置 0x00F3EC60 处。

It seems there is some serious model loading problem.
The sample model is exactly from microsoft tutorial (in my disk the location is give as below)
D:\Windows-Machine-Learning-master\SharedContent\models\SqueezeNet.onnx

This problem is the same as this closed one
https://github.com/microsoft/Windows-Machine-Learning/issues/265
changing the version of the onnx model seems not working.

I tested all the sample onnx models from microsoft, none of them work correctly.

Then I traced a little bit of the code, found that the exception comes from check_hresult(hr) in base.h when I'm using SDK 10.0.18362.0
(path: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt\base.h)
WINRT_EXPORT namespace winrt
{
    template <typename Interface = Windows::Foundation::IActivationFactory>
    auto get_activation_factory(param::hstring const& name)
    {
        impl::com_ref<Interface> object;
        hresult hr = WINRT_RoGetActivationFactory(get_abi(name), guid_of<Interface>(), put_abi(object));

        if (hr == impl::error_not_initialized)
        {
            void* cookie{};
            check_hresult(WINRT_CoIncrementMTAUsage(&cookie));
            hr = WINRT_RoGetActivationFactory(get_abi(name), guid_of<Interface>(), put_abi(object));
        }

        check_hresult(hr);
        return object;
    }
}

it seems that 
hresult hr = WINRT_RoGetActivationFactory(get_abi(name), guid_of<Interface>(), put_abi(object));
will give some negative value  {value=0x80040154 }, I don't know what it means.
thus check_hresult(hr) throw the first exception.

subsequently, the check_hresults in Windows.AI.MachineLearning.h  continues to trigger exceptions.

I also tried SDK 10.0.17763.0, the results are the same.
Testing with Visual Studio 2017 gives similar results.

**Comment by Karnav123** [comment]
Similar issue while loading the model.
`Exception thrown at 0x00007FFAD551A799 in WinMLTest.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0000005C103FEDC8. occurred`

**Comment by Karnav123** [comment]
I am able to load SqueezeNet.onnx model and given sample example is running fine but I developed sklearn and xgboost model for which it is it fails to load the model.

**Comment by martinb35** [comment]
@SpaceView - can you confirm which version of Windows 10 you are on? run "Winver.exe" and you will get a version and OS build number. Since Windows ML is not in older versions of Windows 10, we first want to check to make sure you have it.

@Karnav123 - please open a new issue for the one you mentioned.

closing as this is old, please re-open if you're still seeing issues.
