### ISSUE TITLE
Same model (Unet-like) is 5x slower on WinML than it is on CoreML when running on GPU.

### ISSUE THREAD

**Issue by vlj** [microsoft/Windows-Machine-Learning#284]
We have a Unet convolutional network that we want to integrate to an existing app. The network was trained on tensorflow and the app has a mac and a windows version, so we rely on CoreML and WinML for that purpose.

We used the tool provided by both framework to convert from the tensorflow format to the one supported by the platform eg mlmodel on mac and onnx on Windows. The conversion is rather straightforward ; the onnx network was also further optimised by using half float format.

We based our windows implementation on the CustomTensorisation sample because we have 16 bits image as input. Otherwise it's rather straightforward too, we fill a TenforFloat16 object, we pass it to our network, and the collect the result.

The networks is a Unet with classic operators like convolution and deconvolution, maxpools...

When running inference on CPU the performance are very close between CoreML and WinML.

## Current behavior

The issue is that the WinML implementation is on average 5 times slower than the CoreML one on GPU. We don't have exactly the same hardware for mac and windows machine but for reference:
 on a sample image a RX 575 with 4 GB of VRAM takes 20 seconds to process on CoreML ; for the same image, a RX 560 with 4Gb of VRAM takes 150seconds. While the the 560 is slower than the 575 it's not that much slower.
With the same image and a RTX 2070 which should significatively outperform the RX 575, it takes 30seconds for winML to process the image.

Using PIX I traced the execution on the RTX 2070 and we spent 27s (on 30) in the convolution operators on this card , despite WinML issuing Meta command which should be supported by the rtx 2070 (I use latest drivers as of writing, 441.48).

## Expected behavior

Not such a big performance gap between coreml and winml for the same network on GPU.

## Environment

1863.449 (19H2)

WinMLTools specific:
	-  Trained on tensorflow

Visual Studio 
- [ ] 2017 (version: 15.9.17)

**Comment by edmBernard** [comment]
Any help on this ? I also observe a difference between WinML and OnnxRuntime where WinML is at least 3 times slower

**Comment by martinb35** [comment]
@vlj and @edmBernard - we have made many performance improvements in the last several months that will be available in the next release of Windows (available in prerelease builds now). Alternatively, you can try our [NuGet package](https://www.nuget.org/packages/Microsoft.AI.MachineLearning), which is not tied to Windows releases to stay even more current with our performance improvements. You can find a helpful doc on migrating to the NuGet package [here](https://docs.microsoft.com/en-us/windows/ai/windows-ml/port-app-to-nuget).
