### ISSUE TITLE
Python Inference for the Winml

### ISSUE THREAD

**Issue by hezhangsprinter** [microsoft/Windows-Machine-Learning#288]
Hi 
    Is there python wrapper that we can use to reproduce the winml inferencing like coreml does? 

Best

**Comment by hezhangsprinter** [comment]
For example, 
       For this function, I get image in numpy array 
      "image = cv2.imread(name)" 
       How could I transfer the numpy array to the VideoFrame.  Like, the in the xlang tutorial, the image is transferred  to bitmap and then Videoframe.  

async def load_image_file(file_path):
    file = await StorageFile.get_file_from_path_async(os.fspath(file_path))
    stream = await file.open_async(FileAccessMode.READ)
    decoder = await BitmapDecoder.create_async(stream)
    software_bitmap = await decoder.get_software_bitmap_async()
    return VideoFrame.create_with_software_bitmap(software_bitmap)



In addition, how to transfer the winml.TensorFloat to numpy array? 

Best

**Comment by Adele101** [comment]
Hello,
Windows ML supports C# and C++ for inferencing. The xlang tutorial you mention is unfortunately out of date and not officially supported.
Thanks!
