### ISSUE TITLE
Missing ONNX OpSet 11,required for repo: segmentation_models.pytorch FPN

### ISSUE THREAD

**Issue by samhodge** [microsoft/Windows-Machine-Learning#322]
## Current behavior
I have converted a `.pth` model that has been frozen and converted to a `.onnx` file using code similar to:

```
model = project.model.get_model(num_classes=NUM_CLASSES,multi=MULTI)

PATH = "./runs_checkpoints_1593587460_checkpoint_100.pth"

checkpoint=torch.load(PATH, map_location = torch.device(DEVICE))

model.load_state_dict(checkpoint['model'])
    
model.eval()

MODEL_DIM = 320
BATCH_SIZE = 1
CHANNELS = 3

dummy_input = torch.randn(BATCH_SIZE, 
                          CHANNELS,
                          MODEL_DIM,
                          MODEL_DIM,
                          device='cpu')

input_names = [ "input/input.1" ] 
output_names = [ "output/output.1" ]

torch.onnx.export(model, 
                  dummy_input,
                  PATH.replace(".pth",".onnx"), 
                  verbose=True, input_names=input_names, 
                  output_names=output_names,
                  opset_version=11,)
```

Results in

```
Exception thrown at 0x00007FFD3A8C9149 in TestML.exe: Microsoft C++ exception: onnx::checker::ValidationError at memory location 0x00000023A26FF030.
Exception thrown at 0x00007FFD3A8C9149 (KernelBase.dll) in TestML.exe: WinRT originate error - 0x80004005 : 'Unrecognized attribute: ceil_mode'.
```

## Expected behavior

I would hope to be able to run FPN with ResNext from https://github.com/qubvel/segmentation_models.pytorch

Even is that Requires OpSet 10 or 11

## Minimal reproduction of the problem with instructions

Follow this tutorial

https://github.com/qubvel/segmentation_models.pytorch/tree/master/examples

Export a `.onnx` model, try to run inference in WinML

## Environment

Windows Build Number:  17763.379

App min and target version: 10.0.17763.0

OS Version (Server, IoT Core, Desktop, etc): Window 10 Pro 1809 

Graphics Driver version: 26.21.14.24.292

DxDiag:
[DxDiag.txt](https://github.com/microsoft/Windows-Machine-Learning/files/4876696/DxDiag.txt)

Visual Studio 
-  Microsoft Visual Studio Community 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA441
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.954.58314
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.6.954.58314
Azure App Service Tools v3.0.0

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IncrediBuild Build Acceleration   1.5.0.13
IncrediBuild effectively reduces compilation and development times by up to 90%.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by samhodge** [comment]
Any update?

**Comment by Adele101** [comment]
Hello! ONNX OpSet 10 is supported for CPU in Windows 10, 2004. 
ONNX OpSet 10 and 11 are also currently supported in the [NuGet package](https://github.com/microsoft/Windows-Machine-Learning/issues/322)

**Comment by samhodge** [comment]
I would have thought I had the latest NuGet package 


I will confirm, sorry for the noise

Sam

**Comment by samhodge** [comment]
Can you link me to the release notes for which NuGet package has which ONNX instructions?

I am having difficulty navigating the release notes 2004 is that a version number or a date?

**Comment by robinvanemden** [comment]
> Can you link me to the release notes for which NuGet package has which ONNX instructions?
> 
> I am having difficulty navigating the release notes 2004 is that a version number or a date?

2004 is a Windows 10 release version:

"Windows 10, version 2004, also known as the Windows 10 May 2020 Update"

https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-2004

**Comment by samhodge** [comment]
I have installed the NuGet package and I am getting the same error.

**Comment by samhodge** [comment]
Here is the release date for the NuGet package:

Saturday, July 18, 2020 (7/18/2020)

**Comment by samhodge** [comment]
An example model is here

https://github.com/samhodge/segmentation_models.pytorch/blob/master/examples/best_model.onnx.zip

Inference in onnx runtime in Python on Linux and C++ has been tested with this model

**Comment by martinb35** [comment]
hi @samhodge, the NuGet version you have does support opset 10 and 11, as you can see on the compatibility support table [here](https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md#compatibility). As for the error you're seeing, please open an issue in the [OnnxRuntime repo](https://github.com/microsoft/onnxruntime/issues) as the error is coming from the underlying engine.
