### ISSUE TITLE
WinMLRunner - remove 5D block on GPU (bug)

### ISSUE THREAD

**Issue by fdwr** [microsoft/Windows-Machine-Learning#324]
## Current behavior
WinMLRunner rejects 5D tensors, with the message "Input feature input shape is too large. GPU path only accepts tensor dimensions <= 4 : 5", even though DirectML supports 5D tensors (and will likely support more than that too).

https://github.com/microsoft/Windows-Machine-Learning/blob/master/Tools/WinMLRunner/src/Run.cpp#L296

## Expected behavior
WinMLRunner should just let any dimension count through - let the API decide if it is support or not.

## Minimal reproduction of the problem with instructions
Any model with 5D bindings.

`WinMLRunner.exe -gpu -model unet3d.channels_first.keras2onnx.onnx`

(source is models.zip from here: https://github.com/microsoft/Windows-Machine-Learning/issues/215)

## Environment

Windows Build Number: 18363.900

App min and target version: Current master, commit 8ca3e52 on 2019 Oct 15

OS Version (Server, IoT Core, Desktop, etc): Desktop

Graphics Driver version: <any>

DxDiag: <NA>

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: NA)
- [ ] 2017 Preview (version: NA)

**Comment by ryanlai2** [comment]
Released WinMLRunner with bug fix: https://github.com/microsoft/Windows-Machine-Learning/releases/tag/1.2.1.2
