### ISSUE TITLE
Fix Documentation for -DebugEvaluate

### ISSUE THREAD

**Issue by hahnicity** [microsoft/Windows-Machine-Learning#326]
# Documentation Bug for -DebugEvaluate

## Current behavior
Current README.md file describes old behavior for WinMLRunner.exe. The current docs have code example

```
logman start winml -ets -o winmllog.etl -nb 128 640 -bs 128
logman update trace  winml -p {BCAD6AEE-C08D-4F66-828C-4C43461A033D} 0xffffffffffffffff 0xff -ets         
WinMLRunner.exe -model C:\Repos\Windows-Machine-Learning\SharedContent\models\SqueezeNet.onnx -debug
logman stop winml -ets
```
This is out of date. The `-debug` flag was removed in favor of `-DebugEvaluate`

## Expected behavior
Please describe use of this flag via the command line, or via use of WinML Dashboard.

**Comment by Adele101** [comment]
Thank you for pointing this out, the documentation has been updated.

**Comment by martinb35** [comment]
closing per @Adele101's comment.
