### ISSUE TITLE
Add Support for Benchmarking Layer Inference Timing

### ISSUE THREAD

**Issue by hahnicity** [microsoft/Windows-Machine-Learning#329]
# Feature Request For Benchmarking Layer Inference Timing

Currently WinML Dashboard supports debugging for individual layer outputs. However it would be extremely helpful from a model inference performance testing perspective if we could also performance test time it takes individual layers to execute. This might help lead to insight on layers that we might be interested in pruning, or even places that WinML/DirectML can implement specific performance improvements in the future.

**Comment by martinb35** [comment]
thanks for opening this, we're pulling together some documentation to try to help out here. In the meantime, you can start collecting logs by following the instructions [for using logman and WPA](https://stackoverflow.com/questions/52977756/exception-the-parameter-is-incorrect-when-attempting-to-run-an-onnx-model-wi/53549244) or [PIX and DirectML](https://devblogs.microsoft.com/pix/pix-1810-02-direct3d11-and-winml/).
