### ISSUE TITLE
Time-consuming issues of WinML When running onnx inference continuously

### ISSUE THREAD

**Issue by wangchao1013** [microsoft/Windows-Machine-Learning#331]
I want to process continuous video frame data, but I found a strange phenomenon: when the model is called continuously for inference, the time consumption of WinML will increase as the time interval between two inferences increases. Do you have any suggestions?
####  Sleep(1)
```
    for (int i = 0; i < 1000; i++)
    {
        Sleep(1);
        startTime = StartDetectionTime();
        results = session.Evaluate(binding, L"RunID");
        FinishDetectionTime("WinML", startTime);
    }
```
![image](https://user-images.githubusercontent.com/34050323/88126130-73eb7380-cc03-11ea-8c07-07a52a4a0fb8.png)
####  Sleep(20)
![image](https://user-images.githubusercontent.com/34050323/88126045-456d9880-cc03-11ea-97d0-b5fde0c7729f.png)
####  Sleep(100)
![image](https://user-images.githubusercontent.com/34050323/88126102-633afd80-cc03-11ea-9958-e32fef6925c3.png)

**Comment by ryanlai2** [comment]
Hi @wangchao1013 , thanks for reporting this issue! May I ask what LearningModelDeviceKind are you using to produce this phenomenon?

**Comment by ryanlai2** [comment]
Hi @wangchao1013 , regardless of LearningModelDeviceKind CPU or DirectX, power management can affect the evaluation performance and result in slower evaluation if there is too much ample time in between evaluates.

Typically in the CPU case, changing the power plan or just the minimum cpu frequency in power plan settings will affect the performance. In the GPU case, vendor-specific GPU power management settings can also affect as well.

Thanks,
Ryan
