### ISSUE TITLE
Onnx model runs on CPU but not on GPU

### ISSUE THREAD

**Issue by cjtrueeb** [microsoft/Windows-Machine-Learning#334]
OS Platform and Distribution: Windows 10
    Visual Studio 2019
    GPU model and memory: Radeon Rx 580 Series (8Gb)

I used the Tensorization sample to transfer my Tensor from CPU to GPU in order to use DirectX for the model inference. My model runs perfectly fine on the CPU but on the GPU I am getting wrong outputs (all zeros).
During inference the following exception is raised;
```onecoreuap\windows\windowsai\common\operatorauthorhelper\mloperatorauthorhelper.h(418)\Windows.AI.MachineLearning.dll!00007FFE5AB2FA13: (caller: 00007FFE5AB2F469) Exception(1) tid(9f4c) 80070057 The parameter is incorrect.``` 

I guess that this exception is handled and is not the source of the problem. Since I used the exact code from the Tensorization sample for the tensor creation, except for a different Tensor shape, I am struggling to find the problem. Is it possible that the example only works with positive numbers (as it is tested with images)? My inputs are centered around zero. Also how can I read out the values stored in a tensor on the GPU? When calling tensor.GetAsVectorView() I get a ```Read access violation (nullptr)``` error and I do not know how to read out the values otherwise.

**Comment by XHatan** [comment]
Hey, @cjtrueeb  I met with the same problem with Radeon Rx 580 Series (8Gb) , how do you solve this issue ?

**Comment by cjtrueeb** [comment]
@XHatan I have closed this issue because I have realised that I do not understand the issue; With different versions of the windows SDK And windows.ai.machinelearning I am getting completely different errors. Also, when I run the Tensorzation sample the inference is slower with DirectX, so is it even using GPU? I am now using the latest microsoft.ai.machinelearning NuGet package, with which I can use DirecX without manually tensorizing; Just feed in the CPU tensor. This runs without error, but it might just fall back to GPU operators and simply handle the exceptions without printing them out.
Let me please know if you have any news on this!

**Comment by cjtrueeb** [comment]
With the most recent microsoft.ai.machinelearning package there are no exceptions raised, but the execution on CPU (default) and GPU (DirectX) are exactly the same and the output says:
`onecore\windows\directx\dxcore\dll\dxcore.cpp(949)\dxcore.dll!00007FFA10D9A9C9: (caller: 00007FF9A44F0DA8) ReturnHr(1) tid(4d40) 80004002 No such interface supported`

**Comment by martinb35** [comment]
hi @cjtrueeb - we believe this is fixed in the latest NuGet package 1.5.2 [here](https://www.nuget.org/packages/Microsoft.AI.MachineLearning/1.5.2). If you are still seeing this, can you also report what OS version you are on?  (run "winver.exe" and there's a version number and an OS Build number.) and which edition (home, professional, enterprise, etc.)? 
Also, which LearningModelDevice enum are you using? Could be one of DirectX, DirectXHighPerformance, DirectXMinPower.

If you have sample code or a repo we can look at, that would be helpful too. Thanks!
