### ISSUE TITLE
Model generated by Object Detection (Azure ML via ML.NET) does not work with Windows.AI.MachineLearning libraries

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/Windows-Machine-Learning#350]
Hi Team! I raised this issue ([#5402](https://github.com/dotnet/machinelearning/issues/5402)) and got to know that this is not related to ML.NET. 

So the little background is, I downloaded this model (ONNX) using Azure ML via ML.NET but when I try to use it within my UWP app, it gives me an error. 

### System information

- **Windows 10 / 19041.329*
- **UWP**

### Issue

- **I tried to use the ONNX model created by ML.NET Object Detection (Azure ML)**
- **I gave me an error**
- **It must have worked fine**

### Source code / logs

Here's the issue I get; I have tried using last 3 builds and it works well with other ONNX models. 

![image](https://user-images.githubusercontent.com/16351038/93669522-30649700-fad8-11ea-9efa-1bb75339ffad.png)

![image](https://user-images.githubusercontent.com/16351038/93728279-90eff300-fc02-11ea-97a5-01c280804e9a.png)

Stack Trace:

`   at Windows.AI.MachineLearning.LearningModelSession..ctor(LearningModel model)
   at CodeProject01.ObjectDetection.<Init>d__8.MoveNext() in C:\Users\ArafatTehsin\source\repos\Custom Vision\Demos\CodeProject01\ObjectDetection.cs:line 90
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CodeProject01.MainPage.<InitModel>d__13.MoveNext() in C:\Users\ArafatTehsin\source\repos\CustomVision\Demos\CodeProject01\MainPage.xaml.cs:line 61`

**[Model Dropbox Link](https://www.dropbox.com/s/razibb20hx3edsa/bestModel.zip?dl=0)**

**Comment by martinb35** [comment]
hi @arafattehsin, the model you are using is newer than what the OS you are using can support. The table of compatibility lives [here](https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md#compatibility). You can see that operator set 11 and IR version 6 is not yet supported by a released version of Windows. The model is supported in prerelease insider flights, and by the [NuGet package of Windows Machine Learning](https://www.nuget.org/packages/Microsoft.AI.MachineLearning). For more information about using the NuGet package, see the docs [here](https://docs.microsoft.com/en-us/windows/ai/windows-ml/port-app-to-nuget).

**Comment by arafattehsin** [comment]
Hi @martinb35 - My apologies for responding back late but I appreciate your response.

**Comment by martinb35** [comment]
@arafattehsin - no worries, I was pretty late on the initial response too :). Hope this works out for you!
