### ISSUE TITLE
The result of TensorFloat.GetReference() can't be disposed

### ISSUE THREAD

**Issue by ianier** [microsoft/Windows-Machine-Learning#356]
According to the [doc](]https://docs.microsoft.com/en-us/uwp/api/windows.ai.machinelearning.tensorfloat.createreference?view=winrt-19041) the IMemoryBufferReference instance returned by TensorFloat.GetReference() must be disposed prior to evaluation. 

However, the following code throws an exception at the Dispose() call:
`
var tf = Windows.AI.MachineLearning.TensorFloat.Create(new[] { 100L });
var r = tf.CreateReference();
r.Dispose();
`
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'System.IDisposable'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{805D7A98-D4AF-3F0F-967F-E5CF45312D2C}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
  Source=System.Private.CoreLib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at System.IDisposable.Dispose()
   at TensorFlowTest.Program.<Main>d__0.MoveNext() in G:\Projects\AI\TensorFlowTest\TensorFlowTest\Program.cs:line 55

## Expected behavior
The call to Dispose() should not crash.

## Minimal reproduction of the problem with instructions
Copy & paste the code above into a new project.

## Environment
Assembly Windows.AI.MachineLearning.MachineLearningContract, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// C:\Users\...\.nuget\packages\microsoft.windows.sdk.contracts\10.0.19041.1\ref\netstandard2.0\Windows.AI.MachineLearning.MachineLearningContract.winmd

Windows Build Number: 19041

Visual Studio 2019 Community 16.7.5

**Comment by martinb35** [comment]
Thanks for reporting @ianier, we are looking into this now.

**Comment by martinb35** [comment]
closing per @smk2007 's fix in the onnxruntime repo.
