### ISSUE TITLE
Unable to find the input column "data"

### ISSUE THREAD

**Issue by Sindreedelange** [microsoft/Windows-Machine-Learning#358]
## I'm submitting a…

Bug report (I searched for similar issues and did not find one)

## Current behavior

I have followed this [tutorial ](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx) to implement an object detection solution in C#. However, I would like to use a model I've trained on Azure's Custom Vision platform. Therefore I've made some changes to the number of labels, colors, etc. and also `TinyYoloModelSettings.ModelInput` and `TinyYoloModelSettings.ModelOutput` from `image` and `grid`, to `data` and `model_outputs0`, respectively. 

I have verified in numerous different ways the name of the in- and output node using:
1. WinML Dashboard:
![image](https://user-images.githubusercontent.com/9415625/95861159-5d1b6f80-0d61-11eb-8dad-179090c3bc47.png)
2. Printing in Python, 1:
![image](https://user-images.githubusercontent.com/9415625/95861250-77554d80-0d61-11eb-8afa-873035ade837.png)
3. Printing in Python, 2:
![image](https://user-images.githubusercontent.com/9415625/95861314-889e5a00-0d61-11eb-8e40-67caf0b26a41.png)

And so on.. 

More specifically, I get the error message
```
System.ArgumentOutOfRangeException: Could not find input column 'data' (Parameter 'inputSchema')
   at Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator.GetOutputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Data.EstimatorChain`1.GetOutputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
```

It seems like I am not the only one with this problem: https://stackoverflow.com/questions/57264865/cant-get-input-column-name-of-onnx-model-to-work

## Expected behavior

The desired behavior is that the `mlContext.Transforms.ApplyOnnxModel()` function accepts the seemingly correct name of the input node

## Environment

Windows Build Number: 19041.508

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by tiagoshibata** [comment]
Hello @Sindreedelange! The ML.NET repository is https://github.com/dotnet/machinelearning, they should be able to help you there.
