### ISSUE TITLE
WML SqueezeNetObjectDetection Build Errors

### ISSUE THREAD

**Issue by kaisark** [microsoft/Windows-Machine-Learning#363]
## I'm submitting a…

Build Errors in Visual Studio 2017 - sample project SqueezeNetObjectDetectionNC

## Current behavior

Build Errors in Visual Studio 2017 - sample project SqueezeNetObjectDetectionNC

## Expected behavior
Builds successfully

## Minimal reproduction of the problem with instructions
Open Solution is VS Studio and Build Project

## Environment

Windows Build Number:
18362.1139

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):
Windows 10

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version

Visual Studio 
 2017 (version: 15.9.28): Community Edition

Error Message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'C:\Users\<user>\Downloads\Windows-Machine-Learning-master\Samples\SqueezeNetObjectDetection\UWP\cs\obj\x64\Debug\App.g.i.cs' could not be found.	SqueezeNetObjectDetectionCS	C:\Users\<user>\Downloads\Windows-Machine-Learning-master\Samples\SqueezeNetObjectDetection\UWP\cs\CSC	1	Active
Error		Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'	SqueezeNetObjectDetectionCS	C:\Users\<user>\Downloads\Windows-Machine-Learning-master\Samples\SqueezeNetObjectDetection\UWP\cs\SqueezeNetObjectDetectionCS.csproj		
Error	LNK2019	unresolved external symbol WINRT_IMPL_SetErrorInfo referenced in function "struct winrt::hresult __cdecl winrt::impl::get_runtime_activation_factory<struct winrt::Windows::Foundation::IActivationFactory>(struct winrt::param::hstring const &,void * *)" (??$get_runtime_activation_factory@UIActivationFactory@Foundation@Windows@winrt@@@impl@winrt@@YA?AUhresult@1@AEBUhstring@param@1@PEAPEAX@Z)	SqueezeNetObjectDetectionCPP	C:\Users\<user>\Downloads\Windows-Machine-Learning-master\Samples\SqueezeNetObjectDetection\Desktop\cpp\main.obj	1	
Error	LNK2019	unresolved external symbol WINRT_IMPL_GetErrorInfo referenced in function "struct winrt::hresult __cdecl winrt::impl::get_runtime_activation_factory<struct winrt::Windows::Foundation::IActivationFactory>(struct winrt::param::hstring const &,void * *)" (??$get_runtime_activation_factory@UIActivationFactory@Foundation@Windows@winrt@@@impl@winrt@@YA?AUhresult@1@AEBUhstring@param@1@PEAPEAX@Z)	SqueezeNetObjectDetectionCPP	C:\Users\<user>\Downloads\Windows-Machine-Learning-master\Samples\SqueezeNetObjectDetection\Desktop\cpp\main.obj	1	
Error	LNK1120	2 unresolved externals	SqueezeNetObjectDetectionCPP	C:\Users\<user>\Downloads\Windows-Machine-Learning-master\Samples\SqueezeNetObjectDetection\x64\Debug\SqueezeNetObjectDetectionCPP.exe	1		

![vsstudio-error-wml1](https://user-images.githubusercontent.com/3580312/97913483-59558a00-1d1c-11eb-89fe-c6a2f9df9d3f.png)

**Comment by tiagoshibata** [comment]
Hey @kaisark, thanks for reporting. If you just want to get the sample building, it works for me with VS2017. I reproed your build failure locally with VS 2019 and I'll look into fixing it.

**Comment by tiagoshibata** [comment]
Hey @kaisark, this sample uses the `WINDOWS_WINMD` environment variable to locate Windows metadata files, did you set it before building the project? If you're using the default Windows SDK installation path, `WINDOWS_WINMD` should be `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\[SDK VERSION]\Windows.winmd`
