### ISSUE TITLE
Question : how to get the intermediate data of a evaluation?

### ISSUE THREAD

**Issue by oldoldman** [microsoft/Windows-Machine-Learning#366]
It seems I can just bind to the input/output features returned by LearningModel.InputFeatures and LearningModel.OutputFeatures. Take inception_v1 as an example , I can bind to data_0 and prob_1 only, an attempt to bind to some intermediate node (for example, conv1/7x7_s2_1 ) will fail. So is there some way to bind the intermediate node? Many thanks!!!

**Comment by martinb35** [comment]
hi @oldoldman , please see the [instructions](https://github.com/microsoft/Windows-Machine-Learning/tree/master/Tools/WinMLDashboard#debugging-inference) for how to do this with WinMLDashboard. While you can't bind to the intermediate nodes, you can dump the outputs to disk.
