### ISSUE TITLE
Can not download and install the C++/WinRT extension!

### ISSUE THREAD

**Issue by SpongeBab** [microsoft/Windows-Machine-Learning#385]
About this section,I can not download it.
```
Visual Studio extension for C++/WinRT

    In Visual Studio, select Tools > Extensions and Updates.
    Select Online in the left pane and search for "WinRT" using the search box on the right.
    Select C++/WinRT, click Download, and close Visual Studio.
    Follow the installation instructions, then re-open Visual Studio.

```

I just tried to download from the https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264&ssr=false#review-details
It failed too.

**Comment by SpongeBab** [comment]
I find the reason is because I’m in China.But I can download the other extensions.Can you update the link of the C++/WinRT extension.

**Comment by smk2007** [comment]
Hi SpongeBab,

Can you please provide the error that you see when the failure occurs? Is the download blocked by your browser? Is it a 404?

That will help us troubleshoot.

Thanks,

**Comment by SpongeBab** [comment]
There is not any error.Because There is no response when I click the download button.
Today it is fixed.I can download it.Maybe someone fixed it.
![image](https://user-images.githubusercontent.com/65898238/118382915-5a049c80-b62c-11eb-9a8d-1ad6a5f0ffa0.png)
If the error occurs again I will report to you again.
