### ISSUE TITLE
Failed to load model with error: Unknown model file format version.

### ISSUE THREAD

**Issue by aakrandan** [microsoft/Windows-Machine-Learning#386]
## I'm submitting a…
 Bug report (I searched for similar issues and did not find one) 

## Current behavior

I have created and trained a model using pytorch and then converted it to onnx. But while using it with WinML I am getting this error.
"Failed to load model with error: Unknown model file format version."

The error message is not much descriptive so I am not sure what is going wrong here. 
I will attach the script that I used to create the mode.

[Attachments.zip](https://github.com/microsoft/Windows-Machine-Learning/files/6472515/Attachments.zip)

Could you help me resolve this issue? 

## Expected behavior
The model should be loaded properly with out any error 

## Minimal reproduction of the problem with instructions

Use winMLRunner.exe to test the model, it basically fails to Load and Bind

## Environment

Windows Build Number: 19041.876 (10.0.19041.0)

Visual Studio 
- [x] 2017 (version: )

**Comment by smk2007** [comment]
Hi,

Please refer to the details here regarding opset support in Windows Machine Learning:
https://docs.microsoft.com/en-us/windows/ai/windows-ml/release-notes 

Note that for build 19041 (Windows 10, version 2004)
Support for ONNX 1.4 and opset 9 (CPU and GPU)

I looked at your model and notice that your model is marked as requiring opset 10 and file format version 6.

19041 only has support for file format version 5 and opset 9.

The NuGet package currently has the support you need: https://www.nuget.org/packages/Microsoft.AI.MachineLearning/
Will this work?

**Comment by ALONGNEU** [comment]
Hi @smk2007  I am using this Windows SDK version(19041) and I meet the same question too.
I tried the "ONNX=1.10 and opset=9" combination, but it failed. Is that necessary to ensure both the version of "ONNX=1.4 and opset=9" at same time? 
Sorry that I have less knowledge about this, what's the meaning of the "file format version" in your previous answer?
Could you give some suggestions to me? 
thx
