### ISSUE TITLE
ONNX MODELS NOT WORKING IN WINML

### ISSUE THREAD

**Issue by LalithMovva** [microsoft/Windows-Machine-Learning#390]
Describe the bug
When i'm trying to load onnx model of vision model, its working without problem, But when i tried to load other onnx models such as (transformer models converted to ONNX), i'm getting an issue related to opset version.

RuntimeError: Node:ConstantOfShape_13 No Op or Function registered for ConstantOfShape with domain_version of 10

Urgency
none.

To Reproduce
import asyncio
import os
import winrt
import winrt.windows.ai.machinelearning as winml

winml_content_path = Path.cwd() / "winml_content"

model_path = winml_content_path / "bb-quantized.onnx"

def load_model(model_path):
return winml.LearningModel.load_from_file_path(os.fspath(model_path))

a = load_model(model_path)
print(a)

**Comment by ryanlai2** [comment]
Hi @LalithMovva, Thanks for reaching out. Would you be able to share your model for reproduction purposes?

What Windows Build are you running? Run "winver.exe" should be able to give you that information.

**Comment by dspierre** [comment]
moi j'ai  un  problème avec  onnx  avec  l'application  uwp je  n'arrive  pas  à générer  le  code  C# du modèle  générer  précedament  en  ficher  de  type onnx.
J'ai  bien  suivie  le  tutoriel je  ne  comprend  pas .
Je  réinstalle  visual studio code et  je  vérifie  bien  que  code  generator  est  bien  installer  dans  les  extensions mais  rien.

**Comment by nums11** [comment]
It sounds like you're using version 10 on an unsupported version of Windows. Please refer to this document to see which opset versions are available on which OS versions: https://docs.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions
