### ISSUE TITLE
incorrect initialize model

### ISSUE THREAD

**Issue by olexsahka** [microsoft/Windows-Machine-Learning#396]
## Current behavior:
Im trying use this sample for objecr detection(https://github.com/microsoft/Windows-Machine-Learning/tree/master/Samples/Tutorial%20Samples/YOLOv4ObjectDetection), but when  i inintializing your model(yolov4.onnx),appear this error in Evaluate frame func:
  System.NullReferenceException: "Object reference not set to an instance of an object."
_binding was null.

![image](https://user-images.githubusercontent.com/49623736/124139321-2cff3280-da90-11eb-8615-e4af6664ef6a.png)

this error manifested after initializing model. i think model wasn't correct initialized 

## Environment
Onnx version:
![image](https://user-images.githubusercontent.com/49623736/124140301-08578a80-da91-11eb-8b92-3b29e5b8432a.png)

Windows Build Number:19041

App min and target version:19041

OS Version (Server, IoT Core, Desktop, etc): Desktop W10

Thanks in advance

**Comment by jerryshih1106** [comment]
I have the same problem too, any solutions?

**Comment by nums11** [comment]
This issue should now be resolved as the sample has been changed to use the Microsoft.AI.MachineLearning NuGet package.
