### ISSUE TITLE
[WinMLDashboard] Image.NomimalPixelRange edit have no impact

### ISSUE THREAD

**Issue by aungthetnaing** [microsoft/Windows-Machine-Learning#415]
## I'm submitting a…

 Bug report (I searched for similar issues and did not find one

## Current behavior

I used WinML Dashboard to overwrite Image.NomimalPixelRange to range [-1.1]. But it has no effect in WinML wiml::NominalRangeConverter::NominalRangeConverter (still defaulting to 0-255). No meta data values if loaded in Netro too.

## Expected behavior

Metadata values shall be correctly injected.

## Minimal reproduction of the problem with instructions

Take a ONNX model. Edit and overwrite  Image.NomimalPixelRange to range [-1.1. Then, load into a sample (for example, BatchSupport), Add a breakpoint in wiml::NominalRangeConverter::NominalRangeConverter and check which value is loaded in pixelRange. 

## Environment

Windows Build Number: 19043.1237

App min and target version:
commit: 9a39f9ea (0.7 pre-release)
OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)
        - WinMLTools version : WinML Dashboard : 0.7 Pre-release [9a39f9ea ]
        - WinML : 1.10 (commit :  12515552d1c89121f356862716c82d7cb9c9ac8e)

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019

**Comment by zhangxiang1993** [comment]
It looks like Image.NomimalPixelRange metadata is not saved to the model, which caused WinML take the default NomimalPixelRange.
