### ISSUE TITLE
incorrect parameter failed to load model unknown file format in UWP

### ISSUE THREAD

**Issue by suresheprm** [microsoft/Windows-Machine-Learning#446]
Hi,

I will try to load onnx model in UWP but it fails and error is
"incorrect parameter failed to load model unknown file format in UWP"

Model created using pytorch
Converted through pytorch.onnx convertion

Windows 10 Build version 19043
ML Version 1.10.2

**Comment by smk2007** [comment]
Hi, thanks for your feedback.

You are correct. UWP applications using LoadFromPath were regressed, and will reproduce the issue that you are seeing.
This issue has been resolved with this PR https://github.com/microsoft/onnxruntime/pull/9790, and should be available in the next release of the Microsoft.AI.MachineLearning NuGet package.

**Comment by smk2007** [comment]
Alternatively, this may be an issue with the onnx opset, or IR verison of the model.

Can you share the opset and IR version information? This can be found by inspecting the onnx file in Netron.

**Comment by ryanlai2** [comment]
Hi @suresheprm, can you let us know the error message you get from the debugger?
