### ISSUE TITLE
Custom Tensorization Sample Build Error

### ISSUE THREAD

**Issue by jiading-zhu** [microsoft/Windows-Machine-Learning#452]
## I'm submitting a…

Bug report (I searched for similar issues and did not find one)

## Current behavior
Build error: C2102 '&' requires l-value	

## Expected behavior
Project build should be successful

## Minimal reproduction of the problem with instructions
On newest windows 10 release, when I load the solution in your Custom Tensorization Sample with Visual Studio 2019, I would get the build error stated above. 

## Environment

Windows Build Number: 19042.1415

Visual Studio 
- Microsoft Visual Studio Community 2019 Version 16.11.8

**Comment by linnealovespie** [comment]
Hi @jiading-zhu, [#460](https://github.com/microsoft/Windows-Machine-Learning/pull/460) should address this build error. For future reference, you can also set the [/Zc:referenceBinding](https://docs.microsoft.com/en-us/cpp/build/reference/zc-referencebinding-enforce-reference-binding-rules?view=msvc-170) flag to allow l-value binding.
