### ISSUE TITLE
ILearningModelSessionOptionsNative for setting IntraopNumThreads not available on Windows 10

### ISSUE THREAD

**Issue by triplef** [microsoft/Windows-Machine-Learning#468]
## I'm submitting a…

Bug report (I searched for similar issues and did not find one)

## Current behavior
The `ILearningModelSessionOptionsNative` interface required for setting the IntraopNumThreads as described [here](https://docs.microsoft.com/en-us/windows/ai/windows-ml/native-apis/intraopnumthreads) seems to be only available on Windows 11, but not on Windows 10 (tested on build 19043), even though the documentation says it’s available in build 17763.

## Expected behavior
`ILearningModelSessionOptionsNative` should be available on Windows 10 build 17763 and later.

## Minimal reproduction of the problem with instructions

Run the following code (here using C++/WinRT, but should also apply to other language bindings):
```c
LearningModelSessionOptions options;
auto nativeOptions = options.as<ILearningModelSessionOptionsNative>();
nativeOptions->SetIntraOpNumThreadsOverride(1);
```

This throws an exception "No such interface supported" in the second line.

## Environment

Windows Build Number: 19043

App min and target version: 

OS Version (Server, IoT Core, Desktop, etc): Desktop

Visual Studio 2022 (version: 17.0.2)

**Comment by nums11** [comment]
Sorry for the inconvenience, we'll update the docs to point to the correct build (Windows 11 Build 22000).
