### ISSUE TITLE
WinMLDashboard: Fails to install private Python

### ISSUE THREAD

**Issue by matthewDDennis** [microsoft/Windows-Machine-Learning#471]
I've installed v 0.7.0 and when I try and run convert it

- asks to download a private Python instance
- this fails with
`start downloading python
start downloading pip
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
Error: Child process C:\Users\matth\AppData\Local\WinMLDashboard\python\python.exe exited with code 1
    at ChildProcess.<anonymous> (file:///C:/Users/matth/AppData/Local/WinMLDashboard/app-0.7.0/resources/app/build/static/js/main.5085b59a.js:1:264362)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12): Child process C:\Users\matth\AppData\Local\WinMLDashboard\python\python.exe exited with code 1`

It appears that Python 3.6 has been installed in the private Python install directory appdata\local\winmldashboard\python, not 3.7+

**Comment by nums11** [comment]
Thanks for posting we're looking into this issue.

**Comment by rtoddsullivan** [comment]
@nums11, any news on this? I'm also having this issue.

**Comment by lilhoser** [comment]
Same here, the convert tab does NOT work

**Comment by martinb35** [comment]
Hi, thanks for your interest. Unfortunately, supporting this functionality is on our backlog but not a priority at the moment as there are other converters that can be used instead. In particular, [PyTorch -> Onnx](https://pytorch.org/docs/stable/onnx.html) and [TensorFlow -> Onnx](https://github.com/onnx/tensorflow-onnx).
