### ISSUE TITLE
Support deployment of NLP to windows store

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/Windows-Machine-Learning#481]
You have a great number of samples demonstrating how to deploy CNNs to the windows store.

However, NLP tasks are more difficult to preparing the input for. Most NLP tasks rely on python packages for tokenizers, graphene to phoneme models, etc, which can not be converted to onnx, and would be quite labour intensive to convert by hand to C#/C++.

I though a good solution was to use the win32 `CreateProcess` api to run a python script which uses onnx for inference, and imports python packages for pre-processing. However, there is not much information online about this process, and it seems I will have to figure it out the hard way.

For instance, I'm not sure whether pip installing packages into a virtual environment in the apps sandbox, would be a good idea to investigate.

This would only work for desktop apps, so maybe your not that interested.

**Comment by nums11** [comment]
Thanks for posting. We're putting this on the backlog as something we'll look into in the future.
