### ISSUE TITLE
Crash is seen when creating WinML session

### ISSUE THREAD

**Issue by venki-thiyag** [microsoft/Windows-Machine-Learning#494]
## Environment

Windows Build Number: Windows 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)

App min and target version: Windows 10 and above

OS Version (Server, IoT Core, Desktop, etc): Windows 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)

Graphics Driver version: 30.00.0101.1404

DxDiag:
[DxDiag.txt](https://github.com/microsoft/Windows-Machine-Learning/files/9193737/DxDiag.txt)

WinMLTools specific:
	- TensorFlow

Visual Studio 
- [ ] 2019 (version: Version 16.11.13)

Screen shot of error:
![image (1)](https://user-images.githubusercontent.com/8221785/181125244-d52cf840-fdc4-4835-bc7a-447c4ae81e6a.png)

**Comment by nums11** [comment]
Hi @venki-thiyag could you provide your session creation code as well? Thanks

**Comment by venki-thiyag** [comment]
This issue can be closed, as problem was internal to our implementation.
