### ISSUE TITLE
Windows ML support for **non UWP** apps planned?

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/Windows-Machine-Learning#5]
support for classic apps planned?
thanks..

**Comment by serenaz** [comment]
Windows ML does support classic apps. You can use the mlgen tool to create a model interface, or call the Windows ML APIs. See the documentation for more information: https://docs.microsoft.com/windows/uwp/machine-learning/overview#how-to-develop-with-windows-ml

**Comment by oscarbg** [comment]
Thanks..
Two questions then:

Can provide a Win32 API classic sample C++ app on this repo using WinML.h and WinML.lib shipped on Win 17133 SDK?

Mlgen generates c# or cppx but not c++.. is this planned?

**Comment by resonatevision** [comment]
@serenaz can you point me to some documentation on how to use Windows ML with Win32 classic apps? Do I need to include winrt? I am having trouble understanding how to use generated C++/CX file in a non UWP app.

**Comment by serenaz** [comment]
See https://github.com/MicrosoftDocs/windows-uwp/issues/756
