### ISSUE TITLE
How do I invoke my own Execution provider from winML application?

### ISSUE THREAD

**Issue by GAURAVSH19** [microsoft/Windows-Machine-Learning#503]
## I'm submitting a…

  
Sample app request

## Current behavior
I am using winMLRunner to run CNN models and want to use my own execution provider. Is there a way where I can provide my execution provider using winML application?

**Comment by nums11** [comment]
Hi, thanks for posting. WinML is optimized for the Windows OS and DirectML is the chosen execution provider. If you would like to use your own execution provider, we recommend building ONNX Runtime from source.

**Comment by GAURAVSH19** [comment]
@nums11 Thank you for the response, I have already build ONNX Runtime from source and I can see my execution provider in the list of execution providers.  So basically I can see 2 execution providers in the list now -

1) CPUExecutionProvider(default)
2) TestExecutionProvider(Added by me).

When I do inferencing now using WinMlRunner application, I see that CPUExecutionProvider(default) is used, Can you help me with a Sample app which can help in changing the Execution Provider.

Thanks in Advance !!!

**Comment by ryanlai2** [comment]
Hi,

Onnxruntime provides a similar tool to WinMLRunner called [Onnxruntime Perf Test](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/test/perftest) in which target execution provider can be provided as an argument. 

You can see if you can modify the source and build the tool to use your TestExecutionProvider. See the commandline parser [here](https://github.com/microsoft/onnxruntime/blob/b4853a978a7a1caa9d89bc33d547dffc13a7ed26/onnxruntime/test/perftest/command_args_parser.cc#L167)

You can provide your own specific input tensor with protobuf pb file or you can generate an input tensor with [-I flag](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/perftest/command_args_parser.cc#L34).

**Comment by GAURAVSH19** [comment]
@ryanlai2 As far as I understand your comment, Onnxruntime perf test can be used to test Onnxruntime. What I am looking for is winml using my execution provider. Does winmlrunner have an option to select execution provider.

**Comment by nums11** [comment]
Thanks for your response. WinML Runner only allows selecting between CPU or DirectX. If you would like to use a custom execution provider, you would have to modify the WinML source. Currently there is no sample that does this, but referencing how the DirectML device is created may help.
