### ISSUE TITLE
Unsupported opset error message

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/Windows-Machine-Learning#509]
## Current behavior

At the moment DirectML only supports opsets 7-12 https://learn.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions.

However, if you use an onnx model for opset 13, it works with `LearningModelDeviceKind::Cpu`, but with `LearningModelDeviceKind::DirectX` the call to `LearningModelSession.Evaluate` fails with
>C:\apilot\agent\_work\6\s\engine\lotus\onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp(381)\onnxruntime.dll!00007FFE69DD5671: (caller: 00007FFE69DD58EC) Exception(1) tid(1a04) 80070057 The parameter is incorrect.

Which is not very helpful

## Expected behavior

WinML warns that onnx file's opset is not supported for DirectX when model is loaded.

**Comment by nums11** [comment]
Thanks for posting. Usually, there is more descriptive output with the debugger as to what the error should be. Please try re-running the model with the debugger attached. In the meanwhile, we're looking into ways to make the error message more helpful.

**Comment by tom-huntington** [comment]
I can't reproduce this any more. Got no idea why.

btw, It was running with the debugger.
