### ISSUE TITLE
How do I build an ONNX file that does the image scaling and format conversion?

### ISSUE THREAD

**Issue by qunliu** [microsoft/Windows-Machine-Learning#517]
Thanks for adding this [sample code](https://github.com/microsoft/Windows-Machine-Learning/pull/480) to showcase binding and inferencing on DX resources using ORT. I have a couple of questions:

1) The sample code uses dx_preprocessor_efficient_net.onnx for image scaling and convertion from 4 channel data to 3 channel data, however I don't find code that tells how I may build this type of onnx myself, for example, I may need to scale the image differently + some other data format conversion besides doing channel reduction. Would @nums11 please point me to some sample code that does it?

2) Follow-up question on 1), any performance gain using dx_preprocessor_efficient_net.onnx to do this job vs building a compute shader to do it directly?

3) This [sample code](https://github.com/microsoft/Windows-Machine-Learning/blob/master/Samples/WinMLSamplesGallery/WinMLSamplesGalleryNative/ORTHelpers.cpp#L54) provides a way for us to use low level ORT code directly for model loading/binding/inferencing etc even within WinML framework (using DML EP), my question is can we use other EPs (eg: CUDA, TensorRT etc) directly as well this way? Or my question is: how do we leverage EPs other than DML within WinML framework, or using ORT without WinML is the only way to achieve that?

I asked a lot of questions, but I'd really appreciate it if you could point me to the right directions. Thanks in advance!

**Comment by nums11** [comment]
Thanks for posting.

1. The preprocessing model used in the sample was created using LearningModelBuilder which is part of the [WinML Experimental API](https://github.com/microsoft/onnxruntime/blob/5fbfca3d58b88d0da29c6b206c36980052a4392c/winml/api/Microsoft.AI.MachineLearning.Experimental.idl#L79). An example of using LearningModelBuilder to create a model can be found [here](https://github.com/microsoft/Windows-Machine-Learning/blob/02b586811c8beb1ae2208c8605393267051257ae/Samples/WinMLSamplesGallery/WinMLSamplesGalleryNative/SegmentModel.cpp#L140). Alternatively, you could also use the [ONNX python API](https://onnx.ai/onnx/intro/python.html).

2. Writing a compute shader is possible, but will not be optimized with other shaders in the dml graph. There may be performance gains but it's hard to say.

3. WinML uses DML as a backend. The sample showcases how to use ORT with the DML EP, but ORT can be use with other EPs (CUDA, TensorRT, etc.).

**Comment by qunliu** [comment]
> Thanks for posting.
> 
> 1. The preprocessing model used in the sample was created using LearningModelBuilder which is part of the [WinML Experimental API](https://github.com/microsoft/onnxruntime/blob/5fbfca3d58b88d0da29c6b206c36980052a4392c/winml/api/Microsoft.AI.MachineLearning.Experimental.idl#L79). An example of using LearningModelBuilder to create a model can be found [here](https://github.com/microsoft/Windows-Machine-Learning/blob/02b586811c8beb1ae2208c8605393267051257ae/Samples/WinMLSamplesGallery/WinMLSamplesGalleryNative/SegmentModel.cpp#L140). Alternatively, you could also use the [ONNX python API](https://onnx.ai/onnx/intro/python.html).
> 2. Writing a compute shader is possible, but will not be optimized with other shaders in the dml graph. There may be performance gains but it's hard to say.
> 3. WinML uses DML as a backend. The sample showcases how to use ORT with the DML EP, but ORT can be use with other EPs (CUDA, TensorRT, etc.).

Thanks for your reply @nums11! 

Would you please confirm for the third bullet point above that if we want to use any providers other than DML, we can't use WinML, only a level down using ORT directly is the way to go? I am asking because for your [sample code](https://github.com/microsoft/Windows-Machine-Learning/blob/master/Samples/WinMLSamplesGallery/WinMLSamplesGalleryNative/ORTHelpers.cpp#L54), the [ORT API](https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a3ee641b90dd4355c8a27aa84248e4c34) specifically mentions only DML is supported at this moment. Thanks!

**Comment by nums11** [comment]
Yes, if you want to use a provider other than DML you cannot use WinML and you can use ORT. Here is an [example from the ORT docs](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#samples) of using ORT with CUDA as a backend.

**Comment by qunliu** [comment]
> Yes, if you want to use a provider other than DML you cannot use WinML and you can use ORT. Here is an [example from the ORT docs](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#samples) of using ORT with CUDA as a backend.

Thanks for your reply @nums11!
