### ISSUE TITLE
DML command does not exit if Wrong Model path is provided 

### ISSUE THREAD

**Issue by rajasekhar-bandaru** [microsoft/Windows-Machine-Learning#519]
STEPS TO REPRODUCE
1. Download and extracted latest official DML [package](https://github.com/Microsoft/Windows-Machine-Learning/releases).
2. Run below command with wrong path to the model:

## Current behavior
>MicrosoftMLRunner.exe -model mobilenetv2-7-fp16-optimized.onnx -CPU -perf -iterations 10000
Created LearningModelDevice with CPU device
Warning starting event trace: Trace already started 183
Loading model (path = C:\Users\Local_Admin\Downloads\MicrosoftMLRunner\MicrosoftMLRunner\x64\mobilenetv2-7-fp16-optimized.onnx)...
Load Model: C:\Users\Local_Admin\Downloads\MicrosoftMLRunner\MicrosoftMLRunner\x64\mobilenetv2-7-fp16-optimized.onnx [FAILED]
The system cannot find the file specified.

Above command does not terminate after above error, Need to kill it manually using ctrl + C to exit

## Expected behavior
if wrong model path is given then DML command should gracefully exit with the reason.

**Comment by nums11** [comment]
Thanks for posting. We'll look into this.
