### ISSUE TITLE
Access WinML inference engine / DirectML from Electron apps?

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/Windows-Machine-Learning#520]
I guess we could use WebGPU / wasm-simd from Electron apps via onnxruntime-web, but is it possible to access more heavy and functional WinML inference engine / native Windows onnxruntime / DirectML?

Thank you!

**Comment by nums11** [comment]
Thanks for posting. For an example of how to use WinML from an electron app please refer to one of our tools - [WinML Dashboard](https://github.com/microsoft/Windows-Machine-Learning/tree/master/Tools/WinMLDashboard) - which is built using Electron.

**Comment by vadimkantorov** [comment]
Oh very nice! I suggest that this capability is highlighted and explained more in onnxruntime/onnxruntime-web repo and in this repo :)
