### ISSUE TITLE
Support for ONNX external data

### ISSUE THREAD

**Issue by ahmed605** [microsoft/Windows-Machine-Learning#522]
It would be great if WinML added support for loading models with external data, currently creating a session with a model that has external data results in this error:
```
onnxruntime::Initializer::Initializer !model_path.IsEmpty() was false. model_path must not be empty. Ensure that a path is provided when the model is created or loaded.
```

this happens even if the model was loaded through `LearningModel.LoadFromFilePath`, this is because WinML always uses a stream to initialize the onnx runtime even if it was asked to use a path.

**Comment by nums11** [comment]
Thanks for posting. We'll look into this for the future.

**Comment by ahmed605** [comment]
Thanks for replying, I'm curious why the issue was closed as completed tho, is it moved to the internal tracker instead?

**Comment by nums11** [comment]
Yes, we are tracking this internally
