### ISSUE TITLE
_com_error in winrt::impl::consume_Windows_AI_MachineLearning_ILearningModelSessionFactory

### ISSUE THREAD

**Issue by leo-zspace** [microsoft/Windows-Machine-Learning#524]
## I'm submitting a…

 Bug report (I searched for similar issues and did not find one)

## Current behavior
"_com_error at memory location" noise in check_hresult
Exception thrown at 0x00007FFFF08E4FFC in ml.exe: Microsoft C++ exception: _com_error at memory location 0x00000068814FAE90.
Exception thrown at 0x00007FFFF08E4FFC in ml.exe: Microsoft C++ exception: _com_error at memory location 0x00000068814FB1C8.
Exception thrown at 0x00007FFFF08E4FFC in ml.exe: Microsoft C++ exception: _com_error at memory location 0x00000068814FAE90.

## Expected behavior
Not calling deviceToRunOn with null_ptr and polluting Debug Output with check_hresult messages

## Minimal reproduction of the problem with instructions
    LearningModelSession session = nullptr;
    LearningModelBinding binding = nullptr;
...
    session = LearningModelSession{ model, LearningModelDevice(LearningModelDeviceKind::DirectXHighPerformance) };
    binding = LearningModelBinding{ session };

## Environment

Windows Build Number:
22621.2361
Windows Feature Experience Pack 1000.22674.1000.0
11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):
Windows 11 Pro

Graphics Driver version:
NVIDIA GeForce RTX 3060

DxDiag:

WinMLTools specific:
	- PyTorch / exported to ONNX (proprietary cannot share, belive to be the same on any onnx model)
        - WinMLTools version:
<package id="Microsoft.AI.DirectML" version="1.10.0" targetFramework="native" />
<package id="Microsoft.AI.MachineLearning" version="1.13.1" targetFramework="native" />
<package id="Microsoft.ML.OnnxRuntime.DirectML" version="1.13.1" targetFramework="native" />
<package id="Microsoft.Windows.CppWinRT" version="2.0.230706.1" targetFramework="native" />

Visual Studio 
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.7.4

**Comment by nums11** [comment]
Thanks for posting. This debug output is currently expected.
