### ISSUE TITLE
LearningModelPreview.LoadModelFromStorageFileAsync returning null

### ISSUE THREAD

**Issue by leeprtc** [Microsoft/Windows-Machine-Learning#55]
What would cause LearningModelPreview.LoadModelFromStorageFileAsync to return null?

A valid StorageFile was passed as a parameter. No exception was thrown.

I'm using a model created with Azure Custom Vision service, generated using 
OnnxMLTools 1.2.2.0129 (according to Netron).

This worked before for me on Insider builds. I'm running this on latest Visual Studio 15.8.6 on Windows 10 build 17763.1.

**Comment by kumraj** [comment]
LearningModelPreview is deprecated as it was preview version as mentioned in the doc here. 
https://docs.microsoft.com/en-us/uwp/api/windows.ai.machinelearning.preview.learningmodelpreview

Use the non-preview version. See docs here.
https://docs.microsoft.com/en-us/uwp/api/windows.ai.machinelearning

**Comment by leeprtc** [comment]
Thanks for the update. I was using Visual Studio auto-generated code, which was still using the preview version. May want to update the documentation to note this until Visual Studio updates its support to use the non-preview version.
