### ISSUE TITLE
Value cannot be null error on very first run

### ISSUE THREAD

**Issue by cyberkoolman** [Microsoft/Windows-Machine-Learning#7]
Just built the Win 10 build 1803, and VS 2017 Preview 15.7.0 Preview 2 to run this WinMLExplorer.  No modification made, but upon loading a Circut Board image, getting below error.

{System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at WinMLExplorer.ViewModels.MainViewModel.<>c__DisplayClass31_0.<SetResults>b__0(Object _)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()}

![image](https://user-images.githubusercontent.com/5167152/38113387-c83effc8-3372-11e8-8d6c-3e2f4d97e946.png)

Any suggestions or debugging I can do?

**Comment by simplywilson** [comment]
@cyberkoolman - Thanks for reporting the issue. I can't seem to reproduce this issue with a clean VM. I wonder if you are still hitting this issue consistently or rather this is a one-off. I would love to get to the bottom of this.

**Comment by walrusmcd** [comment]
Closing this issue, this was against the Preview api and we are now shipping the non-preview API .  Please reactivate if it is occurring in the current windows insider builds and converters.
