### ISSUE TITLE
CustomTensorization project's Windows SDK version newer than current released Insider SDK

### ISSUE THREAD

**Issue by infil00p** [Microsoft/Windows-Machine-Learning#72]
## I'm submitting a…

 Bug report (I searched for similar issues and did not find one)

## Current behavior
The current CustomTensorization project's SDK version is set to 10.0.18238.0, and the most recent version that I can get is 10.0.17763.0.  This makes it hard to run the sample.

## Expected behavior
That either the SDK be set to 10.0.17763.0 and be able to be built when copying the correct libraries, or that 10.0.18238.0 be able to be downloaded.

## Minimal reproduction of the problem with instructions
Open the CustomTensorization project in Visual Studio.  Go into the properites of the project and check the Windows SDK version.

## Environment

Windows Build Number: Windows 10 1809
Visual Studio 
- [ x] 2017 (version:15.8.7 )
- [ ] 2017 Preview (version: )

**Comment by zhangxiang1993** [comment]
Thanks for submitting this bug. A fix will be submitted soon.

**Comment by zhangxiang1993** [comment]
This has been fixed. By the way, the minimum required version of SDK was set to 177134. So you can also retarget the solution to any SDK version higher than that.
