### ISSUE TITLE
Details about the MNIST model training?

### ISSUE THREAD

**Issue by satarupaguha11** [Microsoft/Windows-Machine-Learning#8]
The demo code looks great, and I was able to run it without any problem. I am just curious, what the model is. Is it trained with a classifical ML algorithm like SVM, or is it an NN based model? What framework was it trained in?

**Comment by LPBourret** [comment]
Hi,
if you are curious about the structure of the model, you can use [Netron](https://github.com/lutzroeder/Netron) to open the model file and visualize the operator graph.

This CNN model was trained using CNTK, you can refer to the [CNTK example](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/DataSets/MNIST)
