### ISSUE TITLE
The type or namespace name 'AI' does not exist in the namespace

### ISSUE THREAD

**Issue by chanmmn** [Microsoft/Windows-Machine-Learning#9]
When I am trying to build the MNIST_GetStarted I got the error "The type or namespace name 'AI' does not exist in the namespace". Where can I download the SDK or DLL?

When I click on the https://www.microsoft.com/en-my/software-download/windowsinsiderpreviewSDK. It is a borken link.

**Comment by LPBourret** [comment]
Hi,
you can obtain the latest preview SDK from [here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) 
Note that in order to run your app targeting this SDK, you will need the same version of the OS on your host machine.
